// Code generated by scripts/forward-cdk8splus.go; DO NOT EDIT.

// Package cdk8splus36 forward-ports the native cdk8s+ high-level API to the
// Kubernetes 1.36 schema. The high-level API is implemented by cdk8splus34;
// users can use this package together with its version-specific k8s subpackage.
package cdk8splus36

import (
	plus34 "github.com/Chriscbr/purecdk8s/cdk8splus34/v2"
	constructs "github.com/Chriscbr/purecdk8s/constructs/v10"
)

type AbstractPod = plus34.AbstractPod
type AbstractPodProps = plus34.AbstractPodProps
type AddDeploymentOptions = plus34.AddDeploymentOptions
type AddDirectoryOptions = plus34.AddDirectoryOptions
type ApiResource = plus34.ApiResource
type ApiResourceOptions = plus34.ApiResourceOptions
type AwsElasticBlockStorePersistentVolume = plus34.AwsElasticBlockStorePersistentVolume
type AwsElasticBlockStorePersistentVolumeProps = plus34.AwsElasticBlockStorePersistentVolumeProps
type AwsElasticBlockStoreVolumeOptions = plus34.AwsElasticBlockStoreVolumeOptions
type AzureDiskPersistentVolume = plus34.AzureDiskPersistentVolume
type AzureDiskPersistentVolumeCachingMode = plus34.AzureDiskPersistentVolumeCachingMode
type AzureDiskPersistentVolumeKind = plus34.AzureDiskPersistentVolumeKind
type AzureDiskPersistentVolumeProps = plus34.AzureDiskPersistentVolumeProps
type AzureDiskVolumeOptions = plus34.AzureDiskVolumeOptions
type BasicAuthSecret = plus34.BasicAuthSecret
type BasicAuthSecretProps = plus34.BasicAuthSecretProps
type Capability = plus34.Capability
type ClusterRole = plus34.ClusterRole
type ClusterRoleBinding = plus34.ClusterRoleBinding
type ClusterRoleBindingProps = plus34.ClusterRoleBindingProps
type ClusterRolePolicyRule = plus34.ClusterRolePolicyRule
type ClusterRoleProps = plus34.ClusterRoleProps
type CommandProbeOptions = plus34.CommandProbeOptions
type CommonSecretProps = plus34.CommonSecretProps
type ConcurrencyPolicy = plus34.ConcurrencyPolicy
type ConfigMap = plus34.ConfigMap
type ConfigMapProps = plus34.ConfigMapProps
type ConfigMapVolumeOptions = plus34.ConfigMapVolumeOptions
type ConnectionScheme = plus34.ConnectionScheme
type Container = plus34.Container
type ContainerLifecycle = plus34.ContainerLifecycle
type ContainerOpts = plus34.ContainerOpts
type ContainerPort = plus34.ContainerPort
type ContainerProps = plus34.ContainerProps
type ContainerResources = plus34.ContainerResources
type ContainerRestartPolicy = plus34.ContainerRestartPolicy
type ContainerSecurityContext = plus34.ContainerSecurityContext
type ContainerSecurityContextProps = plus34.ContainerSecurityContextProps
type ContainerSecutiryContextCapabilities = plus34.ContainerSecutiryContextCapabilities
type Cpu = plus34.Cpu
type CpuResources = plus34.CpuResources
type CronJob = plus34.CronJob
type CronJobProps = plus34.CronJobProps
type CsiVolumeOptions = plus34.CsiVolumeOptions
type DaemonSet = plus34.DaemonSet
type DaemonSetProps = plus34.DaemonSetProps
type Deployment = plus34.Deployment
type DeploymentExposeViaServiceOptions = plus34.DeploymentExposeViaServiceOptions
type DeploymentProps = plus34.DeploymentProps
type DeploymentStrategy = plus34.DeploymentStrategy
type DeploymentStrategyRollingUpdateOptions = plus34.DeploymentStrategyRollingUpdateOptions
type DnsOption = plus34.DnsOption
type DnsPolicy = plus34.DnsPolicy
type DockerConfigSecret = plus34.DockerConfigSecret
type DockerConfigSecretProps = plus34.DockerConfigSecretProps
type EmptyDirMedium = plus34.EmptyDirMedium
type EmptyDirVolumeOptions = plus34.EmptyDirVolumeOptions
type Env = plus34.Env
type EnvFieldPaths = plus34.EnvFieldPaths
type EnvFrom = plus34.EnvFrom
type EnvValue = plus34.EnvValue
type EnvValueFromConfigMapOptions = plus34.EnvValueFromConfigMapOptions
type EnvValueFromFieldRefOptions = plus34.EnvValueFromFieldRefOptions
type EnvValueFromProcessOptions = plus34.EnvValueFromProcessOptions
type EnvValueFromResourceOptions = plus34.EnvValueFromResourceOptions
type EnvValueFromSecretOptions = plus34.EnvValueFromSecretOptions
type EphemeralStorageResources = plus34.EphemeralStorageResources
type ExposeDeploymentViaIngressOptions = plus34.ExposeDeploymentViaIngressOptions
type ExposeServiceViaIngressOptions = plus34.ExposeServiceViaIngressOptions
type FromServiceAccountNameOptions = plus34.FromServiceAccountNameOptions
type FsGroupChangePolicy = plus34.FsGroupChangePolicy
type GCEPersistentDiskPersistentVolume = plus34.GCEPersistentDiskPersistentVolume
type GCEPersistentDiskPersistentVolumeProps = plus34.GCEPersistentDiskPersistentVolumeProps
type GCEPersistentDiskVolumeOptions = plus34.GCEPersistentDiskVolumeOptions
type Group = plus34.Group
type GrpcProbeOptions = plus34.GrpcProbeOptions
type Handler = plus34.Handler
type HandlerFromHttpGetOptions = plus34.HandlerFromHttpGetOptions
type HandlerFromTcpSocketOptions = plus34.HandlerFromTcpSocketOptions
type HorizontalPodAutoscaler = plus34.HorizontalPodAutoscaler
type HorizontalPodAutoscalerProps = plus34.HorizontalPodAutoscalerProps
type HostAlias = plus34.HostAlias
type HostPathVolumeOptions = plus34.HostPathVolumeOptions
type HostPathVolumeType = plus34.HostPathVolumeType
type HttpGetProbeOptions = plus34.HttpGetProbeOptions
type HttpHeader = plus34.HttpHeader
type HttpIngressPathType = plus34.HttpIngressPathType
type IApiEndpoint = plus34.IApiEndpoint
type IApiResource = plus34.IApiResource
type IClusterRole = plus34.IClusterRole
type IConfigMap = plus34.IConfigMap
type INamespaceSelector = plus34.INamespaceSelector
type INetworkPolicyPeer = plus34.INetworkPolicyPeer
type IPersistentVolume = plus34.IPersistentVolume
type IPersistentVolumeClaim = plus34.IPersistentVolumeClaim
type IPodSelector = plus34.IPodSelector
type IResource = plus34.IResource
type IRole = plus34.IRole
type IScalable = plus34.IScalable
type ISecret = plus34.ISecret
type IServiceAccount = plus34.IServiceAccount
type IStorage = plus34.IStorage
type ISubject = plus34.ISubject
type ImagePullPolicy = plus34.ImagePullPolicy
type Ingress = plus34.Ingress
type IngressBackend = plus34.IngressBackend
type IngressProps = plus34.IngressProps
type IngressRule = plus34.IngressRule
type IngressTls = plus34.IngressTls
type Job = plus34.Job
type JobProps = plus34.JobProps
type LabelExpression = plus34.LabelExpression
type LabelSelector = plus34.LabelSelector
type LabelSelectorOptions = plus34.LabelSelectorOptions
type LabelSelectorRequirement = plus34.LabelSelectorRequirement
type LabeledNode = plus34.LabeledNode
type MemoryResources = plus34.MemoryResources
type Metric = plus34.Metric
type MetricContainerResourceOptions = plus34.MetricContainerResourceOptions
type MetricObjectOptions = plus34.MetricObjectOptions
type MetricOptions = plus34.MetricOptions
type MetricTarget = plus34.MetricTarget
type MountOptions = plus34.MountOptions
type MountPropagation = plus34.MountPropagation
type NamedNode = plus34.NamedNode
type Namespace = plus34.Namespace
type NamespaceProps = plus34.NamespaceProps
type NamespaceSelectorConfig = plus34.NamespaceSelectorConfig
type Namespaces = plus34.Namespaces
type NamespacesSelectOptions = plus34.NamespacesSelectOptions
type NetworkPolicy = plus34.NetworkPolicy
type NetworkPolicyAddEgressRuleOptions = plus34.NetworkPolicyAddEgressRuleOptions
type NetworkPolicyIpBlock = plus34.NetworkPolicyIpBlock
type NetworkPolicyPeerConfig = plus34.NetworkPolicyPeerConfig
type NetworkPolicyPort = plus34.NetworkPolicyPort
type NetworkPolicyPortProps = plus34.NetworkPolicyPortProps
type NetworkPolicyProps = plus34.NetworkPolicyProps
type NetworkPolicyRule = plus34.NetworkPolicyRule
type NetworkPolicyTraffic = plus34.NetworkPolicyTraffic
type NetworkPolicyTrafficDefault = plus34.NetworkPolicyTrafficDefault
type NetworkProtocol = plus34.NetworkProtocol
type NfsVolumeOptions = plus34.NfsVolumeOptions
type Node = plus34.Node
type NodeLabelQuery = plus34.NodeLabelQuery
type NodeTaintQuery = plus34.NodeTaintQuery
type NodeTaintQueryOptions = plus34.NodeTaintQueryOptions
type NonApiResource = plus34.NonApiResource
type PathMapping = plus34.PathMapping
type PercentOrAbsolute = plus34.PercentOrAbsolute
type PersistentVolume = plus34.PersistentVolume
type PersistentVolumeAccessMode = plus34.PersistentVolumeAccessMode
type PersistentVolumeClaim = plus34.PersistentVolumeClaim
type PersistentVolumeClaimProps = plus34.PersistentVolumeClaimProps
type PersistentVolumeClaimTemplateProps = plus34.PersistentVolumeClaimTemplateProps
type PersistentVolumeClaimVolumeOptions = plus34.PersistentVolumeClaimVolumeOptions
type PersistentVolumeMode = plus34.PersistentVolumeMode
type PersistentVolumeProps = plus34.PersistentVolumeProps
type PersistentVolumeReclaimPolicy = plus34.PersistentVolumeReclaimPolicy
type Pod = plus34.Pod
type PodConnections = plus34.PodConnections
type PodConnectionsAllowFromOptions = plus34.PodConnectionsAllowFromOptions
type PodConnectionsAllowToOptions = plus34.PodConnectionsAllowToOptions
type PodConnectionsIsolation = plus34.PodConnectionsIsolation
type PodDns = plus34.PodDns
type PodDnsProps = plus34.PodDnsProps
type PodManagementPolicy = plus34.PodManagementPolicy
type PodProps = plus34.PodProps
type PodScheduling = plus34.PodScheduling
type PodSchedulingAttractOptions = plus34.PodSchedulingAttractOptions
type PodSchedulingColocateOptions = plus34.PodSchedulingColocateOptions
type PodSchedulingSeparateOptions = plus34.PodSchedulingSeparateOptions
type PodSecurityContext = plus34.PodSecurityContext
type PodSecurityContextProps = plus34.PodSecurityContextProps
type PodSelectorConfig = plus34.PodSelectorConfig
type Pods = plus34.Pods
type PodsAllOptions = plus34.PodsAllOptions
type PodsSelectOptions = plus34.PodsSelectOptions
type Probe = plus34.Probe
type ProbeOptions = plus34.ProbeOptions
type Protocol = plus34.Protocol
type Replicas = plus34.Replicas
type Resource = plus34.Resource
type ResourceFieldPaths = plus34.ResourceFieldPaths
type ResourcePermissions = plus34.ResourcePermissions
type ResourceProps = plus34.ResourceProps
type RestartPolicy = plus34.RestartPolicy
type Role = plus34.Role
type RoleBinding = plus34.RoleBinding
type RoleBindingProps = plus34.RoleBindingProps
type RolePolicyRule = plus34.RolePolicyRule
type RoleProps = plus34.RoleProps
type ScalingPolicy = plus34.ScalingPolicy
type ScalingRules = plus34.ScalingRules
type ScalingStrategy = plus34.ScalingStrategy
type ScalingTarget = plus34.ScalingTarget
type SeccompProfile = plus34.SeccompProfile
type SeccompProfileType = plus34.SeccompProfileType
type Secret = plus34.Secret
type SecretProps = plus34.SecretProps
type SecretValue = plus34.SecretValue
type SecretVolumeOptions = plus34.SecretVolumeOptions
type Service = plus34.Service
type ServiceAccount = plus34.ServiceAccount
type ServiceAccountProps = plus34.ServiceAccountProps
type ServiceAccountTokenSecret = plus34.ServiceAccountTokenSecret
type ServiceAccountTokenSecretProps = plus34.ServiceAccountTokenSecretProps
type ServiceBindOptions = plus34.ServiceBindOptions
type ServiceIngressBackendOptions = plus34.ServiceIngressBackendOptions
type ServicePort = plus34.ServicePort
type ServiceProps = plus34.ServiceProps
type ServiceType = plus34.ServiceType
type SshAuthSecret = plus34.SshAuthSecret
type SshAuthSecretProps = plus34.SshAuthSecretProps
type StatefulSet = plus34.StatefulSet
type StatefulSetProps = plus34.StatefulSetProps
type StatefulSetUpdateStrategy = plus34.StatefulSetUpdateStrategy
type StatefulSetUpdateStrategyRollingUpdateOptions = plus34.StatefulSetUpdateStrategyRollingUpdateOptions
type SubjectConfiguration = plus34.SubjectConfiguration
type Sysctl = plus34.Sysctl
type TaintEffect = plus34.TaintEffect
type TaintedNode = plus34.TaintedNode
type TcpSocketProbeOptions = plus34.TcpSocketProbeOptions
type TlsSecret = plus34.TlsSecret
type TlsSecretProps = plus34.TlsSecretProps
type Topology = plus34.Topology
type User = plus34.User
type Volume = plus34.Volume
type VolumeMount = plus34.VolumeMount
type Workload = plus34.Workload
type WorkloadProps = plus34.WorkloadProps
type WorkloadScheduling = plus34.WorkloadScheduling
type WorkloadSchedulingSpreadOptions = plus34.WorkloadSchedulingSpreadOptions

const (
	AzureDiskPersistentVolumeCachingMode_NONE       = plus34.AzureDiskPersistentVolumeCachingMode_NONE
	AzureDiskPersistentVolumeCachingMode_READ_ONLY  = plus34.AzureDiskPersistentVolumeCachingMode_READ_ONLY
	AzureDiskPersistentVolumeCachingMode_READ_WRITE = plus34.AzureDiskPersistentVolumeCachingMode_READ_WRITE
	AzureDiskPersistentVolumeKind_DEDICATED         = plus34.AzureDiskPersistentVolumeKind_DEDICATED
	AzureDiskPersistentVolumeKind_MANAGED           = plus34.AzureDiskPersistentVolumeKind_MANAGED
	AzureDiskPersistentVolumeKind_SHARED            = plus34.AzureDiskPersistentVolumeKind_SHARED
	Capability_ALL                                  = plus34.Capability_ALL
	Capability_AUDIT_CONTROL                        = plus34.Capability_AUDIT_CONTROL
	Capability_AUDIT_READ                           = plus34.Capability_AUDIT_READ
	Capability_AUDIT_WRITE                          = plus34.Capability_AUDIT_WRITE
	Capability_BLOCK_SUSPEND                        = plus34.Capability_BLOCK_SUSPEND
	Capability_BPF                                  = plus34.Capability_BPF
	Capability_CHECKPOINT_RESTORE                   = plus34.Capability_CHECKPOINT_RESTORE
	Capability_CHOWN                                = plus34.Capability_CHOWN
	Capability_DAC_OVERRIDE                         = plus34.Capability_DAC_OVERRIDE
	Capability_DAC_READ_SEARCH                      = plus34.Capability_DAC_READ_SEARCH
	Capability_FOWNER                               = plus34.Capability_FOWNER
	Capability_FSETID                               = plus34.Capability_FSETID
	Capability_IPC_LOCK                             = plus34.Capability_IPC_LOCK
	Capability_IPC_OWNER                            = plus34.Capability_IPC_OWNER
	Capability_KILL                                 = plus34.Capability_KILL
	Capability_LEASE                                = plus34.Capability_LEASE
	Capability_LINUX_IMMUTABLE                      = plus34.Capability_LINUX_IMMUTABLE
	Capability_MAC_ADMIN                            = plus34.Capability_MAC_ADMIN
	Capability_MAC_OVERRIDE                         = plus34.Capability_MAC_OVERRIDE
	Capability_MKNOD                                = plus34.Capability_MKNOD
	Capability_NET_ADMIN                            = plus34.Capability_NET_ADMIN
	Capability_NET_BIND_SERVICE                     = plus34.Capability_NET_BIND_SERVICE
	Capability_NET_BROADCAST                        = plus34.Capability_NET_BROADCAST
	Capability_NET_RAW                              = plus34.Capability_NET_RAW
	Capability_PERFMON                              = plus34.Capability_PERFMON
	Capability_SETFCAP                              = plus34.Capability_SETFCAP
	Capability_SETGID                               = plus34.Capability_SETGID
	Capability_SETPCAP                              = plus34.Capability_SETPCAP
	Capability_SETUID                               = plus34.Capability_SETUID
	Capability_SYSLOG                               = plus34.Capability_SYSLOG
	Capability_SYS_ADMIN                            = plus34.Capability_SYS_ADMIN
	Capability_SYS_BOOT                             = plus34.Capability_SYS_BOOT
	Capability_SYS_CHROOT                           = plus34.Capability_SYS_CHROOT
	Capability_SYS_MODULE                           = plus34.Capability_SYS_MODULE
	Capability_SYS_NICE                             = plus34.Capability_SYS_NICE
	Capability_SYS_PACCT                            = plus34.Capability_SYS_PACCT
	Capability_SYS_PTRACE                           = plus34.Capability_SYS_PTRACE
	Capability_SYS_RAWIO                            = plus34.Capability_SYS_RAWIO
	Capability_SYS_RESOURCE                         = plus34.Capability_SYS_RESOURCE
	Capability_SYS_TIME                             = plus34.Capability_SYS_TIME
	Capability_SYS_TTY_CONFIG                       = plus34.Capability_SYS_TTY_CONFIG
	Capability_WAKE_ALARM                           = plus34.Capability_WAKE_ALARM
	ConcurrencyPolicy_ALLOW                         = plus34.ConcurrencyPolicy_ALLOW
	ConcurrencyPolicy_FORBID                        = plus34.ConcurrencyPolicy_FORBID
	ConcurrencyPolicy_REPLACE                       = plus34.ConcurrencyPolicy_REPLACE
	ConnectionScheme_HTTP                           = plus34.ConnectionScheme_HTTP
	ConnectionScheme_HTTPS                          = plus34.ConnectionScheme_HTTPS
	ContainerRestartPolicy_ALWAYS                   = plus34.ContainerRestartPolicy_ALWAYS
	DnsPolicy_CLUSTER_FIRST                         = plus34.DnsPolicy_CLUSTER_FIRST
	DnsPolicy_CLUSTER_FIRST_WITH_HOST_NET           = plus34.DnsPolicy_CLUSTER_FIRST_WITH_HOST_NET
	DnsPolicy_DEFAULT                               = plus34.DnsPolicy_DEFAULT
	DnsPolicy_NONE                                  = plus34.DnsPolicy_NONE
	EmptyDirMedium_DEFAULT                          = plus34.EmptyDirMedium_DEFAULT
	EmptyDirMedium_MEMORY                           = plus34.EmptyDirMedium_MEMORY
	EnvFieldPaths_NODE_IP                           = plus34.EnvFieldPaths_NODE_IP
	EnvFieldPaths_NODE_NAME                         = plus34.EnvFieldPaths_NODE_NAME
	EnvFieldPaths_POD_ANNOTATION                    = plus34.EnvFieldPaths_POD_ANNOTATION
	EnvFieldPaths_POD_IP                            = plus34.EnvFieldPaths_POD_IP
	EnvFieldPaths_POD_IPS                           = plus34.EnvFieldPaths_POD_IPS
	EnvFieldPaths_POD_LABEL                         = plus34.EnvFieldPaths_POD_LABEL
	EnvFieldPaths_POD_NAME                          = plus34.EnvFieldPaths_POD_NAME
	EnvFieldPaths_POD_NAMESPACE                     = plus34.EnvFieldPaths_POD_NAMESPACE
	EnvFieldPaths_POD_UID                           = plus34.EnvFieldPaths_POD_UID
	EnvFieldPaths_SERVICE_ACCOUNT_NAME              = plus34.EnvFieldPaths_SERVICE_ACCOUNT_NAME
	FsGroupChangePolicy_ALWAYS                      = plus34.FsGroupChangePolicy_ALWAYS
	FsGroupChangePolicy_ON_ROOT_MISMATCH            = plus34.FsGroupChangePolicy_ON_ROOT_MISMATCH
	HostPathVolumeType_BLOCK_DEVICE                 = plus34.HostPathVolumeType_BLOCK_DEVICE
	HostPathVolumeType_CHAR_DEVICE                  = plus34.HostPathVolumeType_CHAR_DEVICE
	HostPathVolumeType_DEFAULT                      = plus34.HostPathVolumeType_DEFAULT
	HostPathVolumeType_DIRECTORY                    = plus34.HostPathVolumeType_DIRECTORY
	HostPathVolumeType_DIRECTORY_OR_CREATE          = plus34.HostPathVolumeType_DIRECTORY_OR_CREATE
	HostPathVolumeType_FILE                         = plus34.HostPathVolumeType_FILE
	HostPathVolumeType_FILE_OR_CREATE               = plus34.HostPathVolumeType_FILE_OR_CREATE
	HostPathVolumeType_SOCKET                       = plus34.HostPathVolumeType_SOCKET
	HttpIngressPathType_EXACT                       = plus34.HttpIngressPathType_EXACT
	HttpIngressPathType_IMPLEMENTATION_SPECIFIC     = plus34.HttpIngressPathType_IMPLEMENTATION_SPECIFIC
	HttpIngressPathType_PREFIX                      = plus34.HttpIngressPathType_PREFIX
	ImagePullPolicy_ALWAYS                          = plus34.ImagePullPolicy_ALWAYS
	ImagePullPolicy_IF_NOT_PRESENT                  = plus34.ImagePullPolicy_IF_NOT_PRESENT
	ImagePullPolicy_NEVER                           = plus34.ImagePullPolicy_NEVER
	MountPropagation_BIDIRECTIONAL                  = plus34.MountPropagation_BIDIRECTIONAL
	MountPropagation_HOST_TO_CONTAINER              = plus34.MountPropagation_HOST_TO_CONTAINER
	MountPropagation_NONE                           = plus34.MountPropagation_NONE
	NetworkPolicyTrafficDefault_ALLOW               = plus34.NetworkPolicyTrafficDefault_ALLOW
	NetworkPolicyTrafficDefault_DENY                = plus34.NetworkPolicyTrafficDefault_DENY
	NetworkProtocol_SCTP                            = plus34.NetworkProtocol_SCTP
	NetworkProtocol_TCP                             = plus34.NetworkProtocol_TCP
	NetworkProtocol_UDP                             = plus34.NetworkProtocol_UDP
	PersistentVolumeAccessMode_READ_ONLY_MANY       = plus34.PersistentVolumeAccessMode_READ_ONLY_MANY
	PersistentVolumeAccessMode_READ_WRITE_MANY      = plus34.PersistentVolumeAccessMode_READ_WRITE_MANY
	PersistentVolumeAccessMode_READ_WRITE_ONCE      = plus34.PersistentVolumeAccessMode_READ_WRITE_ONCE
	PersistentVolumeAccessMode_READ_WRITE_ONCE_POD  = plus34.PersistentVolumeAccessMode_READ_WRITE_ONCE_POD
	PersistentVolumeMode_BLOCK                      = plus34.PersistentVolumeMode_BLOCK
	PersistentVolumeMode_FILE_SYSTEM                = plus34.PersistentVolumeMode_FILE_SYSTEM
	PersistentVolumeReclaimPolicy_DELETE            = plus34.PersistentVolumeReclaimPolicy_DELETE
	PersistentVolumeReclaimPolicy_RETAIN            = plus34.PersistentVolumeReclaimPolicy_RETAIN
	PodConnectionsIsolation_PEER                    = plus34.PodConnectionsIsolation_PEER
	PodConnectionsIsolation_POD                     = plus34.PodConnectionsIsolation_POD
	PodManagementPolicy_ORDERED_READY               = plus34.PodManagementPolicy_ORDERED_READY
	PodManagementPolicy_PARALLEL                    = plus34.PodManagementPolicy_PARALLEL
	Protocol_SCTP                                   = plus34.Protocol_SCTP
	Protocol_TCP                                    = plus34.Protocol_TCP
	Protocol_UDP                                    = plus34.Protocol_UDP
	ResourceFieldPaths_CPU_LIMIT                    = plus34.ResourceFieldPaths_CPU_LIMIT
	ResourceFieldPaths_CPU_REQUEST                  = plus34.ResourceFieldPaths_CPU_REQUEST
	ResourceFieldPaths_MEMORY_LIMIT                 = plus34.ResourceFieldPaths_MEMORY_LIMIT
	ResourceFieldPaths_MEMORY_REQUEST               = plus34.ResourceFieldPaths_MEMORY_REQUEST
	ResourceFieldPaths_STORAGE_LIMIT                = plus34.ResourceFieldPaths_STORAGE_LIMIT
	ResourceFieldPaths_STORAGE_REQUEST              = plus34.ResourceFieldPaths_STORAGE_REQUEST
	RestartPolicy_ALWAYS                            = plus34.RestartPolicy_ALWAYS
	RestartPolicy_NEVER                             = plus34.RestartPolicy_NEVER
	RestartPolicy_ON_FAILURE                        = plus34.RestartPolicy_ON_FAILURE
	ScalingStrategy_DISABLED                        = plus34.ScalingStrategy_DISABLED
	ScalingStrategy_MAX_CHANGE                      = plus34.ScalingStrategy_MAX_CHANGE
	ScalingStrategy_MIN_CHANGE                      = plus34.ScalingStrategy_MIN_CHANGE
	SeccompProfileType_LOCALHOST                    = plus34.SeccompProfileType_LOCALHOST
	SeccompProfileType_RUNTIME_DEFAULT              = plus34.SeccompProfileType_RUNTIME_DEFAULT
	SeccompProfileType_UNCONFINED                   = plus34.SeccompProfileType_UNCONFINED
	ServiceType_CLUSTER_IP                          = plus34.ServiceType_CLUSTER_IP
	ServiceType_EXTERNAL_NAME                       = plus34.ServiceType_EXTERNAL_NAME
	ServiceType_LOAD_BALANCER                       = plus34.ServiceType_LOAD_BALANCER
	ServiceType_NODE_PORT                           = plus34.ServiceType_NODE_PORT
	TaintEffect_NO_EXECUTE                          = plus34.TaintEffect_NO_EXECUTE
	TaintEffect_NO_SCHEDULE                         = plus34.TaintEffect_NO_SCHEDULE
	TaintEffect_PREFER_NO_SCHEDULE                  = plus34.TaintEffect_PREFER_NO_SCHEDULE
)

func AbstractPod_IsConstruct(x interface{}) *bool {
	return plus34.AbstractPod_IsConstruct(x)
}

func ApiResource_API_SERVICES() ApiResource {
	return plus34.ApiResource_API_SERVICES()
}

func ApiResource_BINDINGS() ApiResource {
	return plus34.ApiResource_BINDINGS()
}

func ApiResource_CERTIFICATE_SIGNING_REQUESTS() ApiResource {
	return plus34.ApiResource_CERTIFICATE_SIGNING_REQUESTS()
}

func ApiResource_CLUSTER_ROLES() ApiResource {
	return plus34.ApiResource_CLUSTER_ROLES()
}

func ApiResource_CLUSTER_ROLE_BINDINGS() ApiResource {
	return plus34.ApiResource_CLUSTER_ROLE_BINDINGS()
}

func ApiResource_COMPONENT_STATUSES() ApiResource {
	return plus34.ApiResource_COMPONENT_STATUSES()
}

func ApiResource_CONFIG_MAPS() ApiResource {
	return plus34.ApiResource_CONFIG_MAPS()
}

func ApiResource_CONTROLLER_REVISIONS() ApiResource {
	return plus34.ApiResource_CONTROLLER_REVISIONS()
}

func ApiResource_CRON_JOBS() ApiResource {
	return plus34.ApiResource_CRON_JOBS()
}

func ApiResource_CSI_DRIVERS() ApiResource {
	return plus34.ApiResource_CSI_DRIVERS()
}

func ApiResource_CSI_NODES() ApiResource {
	return plus34.ApiResource_CSI_NODES()
}

func ApiResource_CSI_STORAGE_CAPACITIES() ApiResource {
	return plus34.ApiResource_CSI_STORAGE_CAPACITIES()
}

func ApiResource_CUSTOM_RESOURCE_DEFINITIONS() ApiResource {
	return plus34.ApiResource_CUSTOM_RESOURCE_DEFINITIONS()
}

func ApiResource_Custom(options *ApiResourceOptions) ApiResource {
	return plus34.ApiResource_Custom(options)
}

func ApiResource_DAEMON_SETS() ApiResource {
	return plus34.ApiResource_DAEMON_SETS()
}

func ApiResource_DEPLOYMENTS() ApiResource {
	return plus34.ApiResource_DEPLOYMENTS()
}

func ApiResource_ENDPOINTS() ApiResource {
	return plus34.ApiResource_ENDPOINTS()
}

func ApiResource_ENDPOINT_SLICES() ApiResource {
	return plus34.ApiResource_ENDPOINT_SLICES()
}

func ApiResource_EVENTS() ApiResource {
	return plus34.ApiResource_EVENTS()
}

func ApiResource_FLOW_SCHEMAS() ApiResource {
	return plus34.ApiResource_FLOW_SCHEMAS()
}

func ApiResource_HORIZONTAL_POD_AUTOSCALERS() ApiResource {
	return plus34.ApiResource_HORIZONTAL_POD_AUTOSCALERS()
}

func ApiResource_INGRESSES() ApiResource {
	return plus34.ApiResource_INGRESSES()
}

func ApiResource_INGRESS_CLASSES() ApiResource {
	return plus34.ApiResource_INGRESS_CLASSES()
}

func ApiResource_JOBS() ApiResource {
	return plus34.ApiResource_JOBS()
}

func ApiResource_LEASES() ApiResource {
	return plus34.ApiResource_LEASES()
}

func ApiResource_LIMIT_RANGES() ApiResource {
	return plus34.ApiResource_LIMIT_RANGES()
}

func ApiResource_LOCAL_SUBJECT_ACCESS_REVIEWS() ApiResource {
	return plus34.ApiResource_LOCAL_SUBJECT_ACCESS_REVIEWS()
}

func ApiResource_MUTATING_WEBHOOK_CONFIGURATIONS() ApiResource {
	return plus34.ApiResource_MUTATING_WEBHOOK_CONFIGURATIONS()
}

func ApiResource_NAMESPACES() ApiResource {
	return plus34.ApiResource_NAMESPACES()
}

func ApiResource_NETWORK_POLICIES() ApiResource {
	return plus34.ApiResource_NETWORK_POLICIES()
}

func ApiResource_NODES() ApiResource {
	return plus34.ApiResource_NODES()
}

func ApiResource_PERSISTENT_VOLUMES() ApiResource {
	return plus34.ApiResource_PERSISTENT_VOLUMES()
}

func ApiResource_PERSISTENT_VOLUME_CLAIMS() ApiResource {
	return plus34.ApiResource_PERSISTENT_VOLUME_CLAIMS()
}

func ApiResource_PODS() ApiResource {
	return plus34.ApiResource_PODS()
}

func ApiResource_POD_DISRUPTION_BUDGETS() ApiResource {
	return plus34.ApiResource_POD_DISRUPTION_BUDGETS()
}

func ApiResource_POD_TEMPLATES() ApiResource {
	return plus34.ApiResource_POD_TEMPLATES()
}

func ApiResource_PRIORITY_CLASSES() ApiResource {
	return plus34.ApiResource_PRIORITY_CLASSES()
}

func ApiResource_PRIORITY_LEVEL_CONFIGURATIONS() ApiResource {
	return plus34.ApiResource_PRIORITY_LEVEL_CONFIGURATIONS()
}

func ApiResource_REPLICATION_CONTROLLERS() ApiResource {
	return plus34.ApiResource_REPLICATION_CONTROLLERS()
}

func ApiResource_REPLICA_SETS() ApiResource {
	return plus34.ApiResource_REPLICA_SETS()
}

func ApiResource_RESOURCE_QUOTAS() ApiResource {
	return plus34.ApiResource_RESOURCE_QUOTAS()
}

func ApiResource_ROLES() ApiResource {
	return plus34.ApiResource_ROLES()
}

func ApiResource_ROLE_BINDINGS() ApiResource {
	return plus34.ApiResource_ROLE_BINDINGS()
}

func ApiResource_RUNTIME_CLASSES() ApiResource {
	return plus34.ApiResource_RUNTIME_CLASSES()
}

func ApiResource_SECRETS() ApiResource {
	return plus34.ApiResource_SECRETS()
}

func ApiResource_SELF_SUBJECT_ACCESS_REVIEWS() ApiResource {
	return plus34.ApiResource_SELF_SUBJECT_ACCESS_REVIEWS()
}

func ApiResource_SELF_SUBJECT_RULES_REVIEWS() ApiResource {
	return plus34.ApiResource_SELF_SUBJECT_RULES_REVIEWS()
}

func ApiResource_SERVICES() ApiResource {
	return plus34.ApiResource_SERVICES()
}

func ApiResource_SERVICE_ACCOUNTS() ApiResource {
	return plus34.ApiResource_SERVICE_ACCOUNTS()
}

func ApiResource_STATEFUL_SETS() ApiResource {
	return plus34.ApiResource_STATEFUL_SETS()
}

func ApiResource_STORAGE_CLASSES() ApiResource {
	return plus34.ApiResource_STORAGE_CLASSES()
}

func ApiResource_SUBJECT_ACCESS_REVIEWS() ApiResource {
	return plus34.ApiResource_SUBJECT_ACCESS_REVIEWS()
}

func ApiResource_TOKEN_REVIEWS() ApiResource {
	return plus34.ApiResource_TOKEN_REVIEWS()
}

func ApiResource_VALIDATING_WEBHOOK_CONFIGURATIONS() ApiResource {
	return plus34.ApiResource_VALIDATING_WEBHOOK_CONFIGURATIONS()
}

func ApiResource_VOLUME_ATTACHMENTS() ApiResource {
	return plus34.ApiResource_VOLUME_ATTACHMENTS()
}

func AwsElasticBlockStorePersistentVolume_FromPersistentVolumeName(scope constructs.Construct, id, name *string) IPersistentVolume {
	return plus34.AwsElasticBlockStorePersistentVolume_FromPersistentVolumeName(scope, id, name)
}

func AwsElasticBlockStorePersistentVolume_IsConstruct(x interface{}) *bool {
	return plus34.AwsElasticBlockStorePersistentVolume_IsConstruct(x)
}

func AzureDiskPersistentVolume_FromPersistentVolumeName(scope constructs.Construct, id, name *string) IPersistentVolume {
	return plus34.AzureDiskPersistentVolume_FromPersistentVolumeName(scope, id, name)
}

func AzureDiskPersistentVolume_IsConstruct(x interface{}) *bool {
	return plus34.AzureDiskPersistentVolume_IsConstruct(x)
}

func BasicAuthSecret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.BasicAuthSecret_FromSecretName(scope, id, name)
}

func BasicAuthSecret_IsConstruct(x interface{}) *bool {
	return plus34.BasicAuthSecret_IsConstruct(x)
}

func ClusterRoleBinding_IsConstruct(x interface{}) *bool {
	return plus34.ClusterRoleBinding_IsConstruct(x)
}

func ClusterRole_FromClusterRoleName(scope constructs.Construct, id, name *string) IClusterRole {
	return plus34.ClusterRole_FromClusterRoleName(scope, id, name)
}

func ClusterRole_IsConstruct(x interface{}) *bool {
	return plus34.ClusterRole_IsConstruct(x)
}

func ConfigMap_FromConfigMapName(scope constructs.Construct, id, name *string) IConfigMap {
	return plus34.ConfigMap_FromConfigMapName(scope, id, name)
}

func ConfigMap_IsConstruct(x interface{}) *bool {
	return plus34.ConfigMap_IsConstruct(x)
}

func Cpu_Millis(amount *float64) Cpu {
	return plus34.Cpu_Millis(amount)
}

func Cpu_Units(amount *float64) Cpu {
	return plus34.Cpu_Units(amount)
}

func CronJob_IsConstruct(x interface{}) *bool {
	return plus34.CronJob_IsConstruct(x)
}

func DaemonSet_IsConstruct(x interface{}) *bool {
	return plus34.DaemonSet_IsConstruct(x)
}

func DeploymentStrategy_Recreate() DeploymentStrategy {
	return plus34.DeploymentStrategy_Recreate()
}

func DeploymentStrategy_RollingUpdate(options *DeploymentStrategyRollingUpdateOptions) DeploymentStrategy {
	return plus34.DeploymentStrategy_RollingUpdate(options)
}

func Deployment_IsConstruct(x interface{}) *bool {
	return plus34.Deployment_IsConstruct(x)
}

func DockerConfigSecret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.DockerConfigSecret_FromSecretName(scope, id, name)
}

func DockerConfigSecret_IsConstruct(x interface{}) *bool {
	return plus34.DockerConfigSecret_IsConstruct(x)
}

func EnvValue_FromConfigMap(configMap IConfigMap, key *string, options *EnvValueFromConfigMapOptions) EnvValue {
	return plus34.EnvValue_FromConfigMap(configMap, key, options)
}

func EnvValue_FromFieldRef(fieldPath EnvFieldPaths, options *EnvValueFromFieldRefOptions) EnvValue {
	return plus34.EnvValue_FromFieldRef(fieldPath, options)
}

func EnvValue_FromProcess(key *string, options *EnvValueFromProcessOptions) EnvValue {
	return plus34.EnvValue_FromProcess(key, options)
}

func EnvValue_FromResource(resource ResourceFieldPaths, options *EnvValueFromResourceOptions) EnvValue {
	return plus34.EnvValue_FromResource(resource, options)
}

func EnvValue_FromSecretValue(secretValue *SecretValue, options *EnvValueFromSecretOptions) EnvValue {
	return plus34.EnvValue_FromSecretValue(secretValue, options)
}

func EnvValue_FromValue(value *string) EnvValue {
	return plus34.EnvValue_FromValue(value)
}

func Env_FromConfigMap(configMap IConfigMap, prefix *string) EnvFrom {
	return plus34.Env_FromConfigMap(configMap, prefix)
}

func Env_FromSecret(secret ISecret) EnvFrom {
	return plus34.Env_FromSecret(secret)
}

func GCEPersistentDiskPersistentVolume_FromPersistentVolumeName(scope constructs.Construct, id, name *string) IPersistentVolume {
	return plus34.GCEPersistentDiskPersistentVolume_FromPersistentVolumeName(scope, id, name)
}

func GCEPersistentDiskPersistentVolume_IsConstruct(x interface{}) *bool {
	return plus34.GCEPersistentDiskPersistentVolume_IsConstruct(x)
}

func Group_FromName(scope constructs.Construct, id, name *string) Group {
	return plus34.Group_FromName(scope, id, name)
}

func Group_IsConstruct(x interface{}) *bool {
	return plus34.Group_IsConstruct(x)
}

func Handler_FromCommand(command *[]*string) Handler {
	return plus34.Handler_FromCommand(command)
}

func Handler_FromHttpGet(path *string, options *HandlerFromHttpGetOptions) Handler {
	return plus34.Handler_FromHttpGet(path, options)
}

func Handler_FromTcpSocket(options *HandlerFromTcpSocketOptions) Handler {
	return plus34.Handler_FromTcpSocket(options)
}

func HorizontalPodAutoscaler_IsConstruct(x interface{}) *bool {
	return plus34.HorizontalPodAutoscaler_IsConstruct(x)
}

func IngressBackend_FromResource(resource IResource) IngressBackend {
	return plus34.IngressBackend_FromResource(resource)
}

func IngressBackend_FromService(service Service, options *ServiceIngressBackendOptions) IngressBackend {
	return plus34.IngressBackend_FromService(service, options)
}

func Ingress_IsConstruct(x interface{}) *bool {
	return plus34.Ingress_IsConstruct(x)
}

func Job_IsConstruct(x interface{}) *bool {
	return plus34.Job_IsConstruct(x)
}

func LabelExpression_DoesNotExist(key *string) LabelExpression {
	return plus34.LabelExpression_DoesNotExist(key)
}

func LabelExpression_Exists(key *string) LabelExpression {
	return plus34.LabelExpression_Exists(key)
}

func LabelExpression_In(key *string, values *[]*string) LabelExpression {
	return plus34.LabelExpression_In(key, values)
}

func LabelExpression_NotIn(key *string, values *[]*string) LabelExpression {
	return plus34.LabelExpression_NotIn(key, values)
}

func LabelSelector_Of(options *LabelSelectorOptions) LabelSelector {
	return plus34.LabelSelector_Of(options)
}

func MetricTarget_AverageUtilization(value *float64) MetricTarget {
	return plus34.MetricTarget_AverageUtilization(value)
}

func MetricTarget_AverageValue(value *float64) MetricTarget {
	return plus34.MetricTarget_AverageValue(value)
}

func MetricTarget_Value(value *float64) MetricTarget {
	return plus34.MetricTarget_Value(value)
}

func Metric_ContainerCpu(options *MetricContainerResourceOptions) Metric {
	return plus34.Metric_ContainerCpu(options)
}

func Metric_ContainerEphemeralStorage(options *MetricContainerResourceOptions) Metric {
	return plus34.Metric_ContainerEphemeralStorage(options)
}

func Metric_ContainerMemory(options *MetricContainerResourceOptions) Metric {
	return plus34.Metric_ContainerMemory(options)
}

func Metric_ContainerStorage(options *MetricContainerResourceOptions) Metric {
	return plus34.Metric_ContainerStorage(options)
}

func Metric_External(options *MetricOptions) Metric {
	return plus34.Metric_External(options)
}

func Metric_Object(options *MetricObjectOptions) Metric {
	return plus34.Metric_Object(options)
}

func Metric_Pods(options *MetricOptions) Metric {
	return plus34.Metric_Pods(options)
}

func Metric_ResourceCpu(target MetricTarget) Metric {
	return plus34.Metric_ResourceCpu(target)
}

func Metric_ResourceEphemeralStorage(target MetricTarget) Metric {
	return plus34.Metric_ResourceEphemeralStorage(target)
}

func Metric_ResourceMemory(target MetricTarget) Metric {
	return plus34.Metric_ResourceMemory(target)
}

func Metric_ResourceStorage(target MetricTarget) Metric {
	return plus34.Metric_ResourceStorage(target)
}

func Namespace_IsConstruct(x interface{}) *bool {
	return plus34.Namespace_IsConstruct(x)
}

func Namespace_NAME_LABEL() *string {
	return plus34.Namespace_NAME_LABEL()
}

func Namespaces_All(scope constructs.Construct, id *string) Namespaces {
	return plus34.Namespaces_All(scope, id)
}

func Namespaces_IsConstruct(x interface{}) *bool {
	return plus34.Namespaces_IsConstruct(x)
}

func Namespaces_Select(scope constructs.Construct, id *string, options *NamespacesSelectOptions) Namespaces {
	return plus34.Namespaces_Select(scope, id, options)
}

func NetworkPolicyIpBlock_AnyIpv4(scope constructs.Construct, id *string) NetworkPolicyIpBlock {
	return plus34.NetworkPolicyIpBlock_AnyIpv4(scope, id)
}

func NetworkPolicyIpBlock_AnyIpv6(scope constructs.Construct, id *string) NetworkPolicyIpBlock {
	return plus34.NetworkPolicyIpBlock_AnyIpv6(scope, id)
}

func NetworkPolicyIpBlock_Ipv4(scope constructs.Construct, id, cidr *string, except *[]*string) NetworkPolicyIpBlock {
	return plus34.NetworkPolicyIpBlock_Ipv4(scope, id, cidr, except)
}

func NetworkPolicyIpBlock_Ipv6(scope constructs.Construct, id, cidr *string, except *[]*string) NetworkPolicyIpBlock {
	return plus34.NetworkPolicyIpBlock_Ipv6(scope, id, cidr, except)
}

func NetworkPolicyIpBlock_IsConstruct(x interface{}) *bool {
	return plus34.NetworkPolicyIpBlock_IsConstruct(x)
}

func NetworkPolicyPort_AllTcp() NetworkPolicyPort {
	return plus34.NetworkPolicyPort_AllTcp()
}

func NetworkPolicyPort_AllUdp() NetworkPolicyPort {
	return plus34.NetworkPolicyPort_AllUdp()
}

func NetworkPolicyPort_Of(props *NetworkPolicyPortProps) NetworkPolicyPort {
	return plus34.NetworkPolicyPort_Of(props)
}

func NetworkPolicyPort_Tcp(port *float64) NetworkPolicyPort {
	return plus34.NetworkPolicyPort_Tcp(port)
}

func NetworkPolicyPort_TcpRange(startPort, endPort *float64) NetworkPolicyPort {
	return plus34.NetworkPolicyPort_TcpRange(startPort, endPort)
}

func NetworkPolicyPort_Udp(port *float64) NetworkPolicyPort {
	return plus34.NetworkPolicyPort_Udp(port)
}

func NetworkPolicyPort_UdpRange(startPort, endPort *float64) NetworkPolicyPort {
	return plus34.NetworkPolicyPort_UdpRange(startPort, endPort)
}

func NetworkPolicy_IsConstruct(x interface{}) *bool {
	return plus34.NetworkPolicy_IsConstruct(x)
}

func NewAbstractPod_Override(arg0 AbstractPod, arg1 constructs.Construct, arg2 *string, arg3 *AbstractPodProps) {
	plus34.NewAbstractPod_Override(arg0, arg1, arg2, arg3)
}

func NewAwsElasticBlockStorePersistentVolume(scope constructs.Construct, id *string, props *AwsElasticBlockStorePersistentVolumeProps) AwsElasticBlockStorePersistentVolume {
	return plus34.NewAwsElasticBlockStorePersistentVolume(scope, id, props)
}

func NewAwsElasticBlockStorePersistentVolume_Override(volume AwsElasticBlockStorePersistentVolume, scope constructs.Construct, id *string, props *AwsElasticBlockStorePersistentVolumeProps) {
	plus34.NewAwsElasticBlockStorePersistentVolume_Override(volume, scope, id, props)
}

func NewAzureDiskPersistentVolume(scope constructs.Construct, id *string, props *AzureDiskPersistentVolumeProps) AzureDiskPersistentVolume {
	return plus34.NewAzureDiskPersistentVolume(scope, id, props)
}

func NewAzureDiskPersistentVolume_Override(volume AzureDiskPersistentVolume, scope constructs.Construct, id *string, props *AzureDiskPersistentVolumeProps) {
	plus34.NewAzureDiskPersistentVolume_Override(volume, scope, id, props)
}

func NewBasicAuthSecret(scope constructs.Construct, id *string, props *BasicAuthSecretProps) BasicAuthSecret {
	return plus34.NewBasicAuthSecret(scope, id, props)
}

func NewBasicAuthSecret_Override(secret BasicAuthSecret, scope constructs.Construct, id *string, props *BasicAuthSecretProps) {
	plus34.NewBasicAuthSecret_Override(secret, scope, id, props)
}

func NewClusterRole(scope constructs.Construct, id *string, props *ClusterRoleProps) ClusterRole {
	return plus34.NewClusterRole(scope, id, props)
}

func NewClusterRoleBinding(scope constructs.Construct, id *string, props *ClusterRoleBindingProps) ClusterRoleBinding {
	return plus34.NewClusterRoleBinding(scope, id, props)
}

func NewClusterRoleBinding_Override(binding ClusterRoleBinding, scope constructs.Construct, id *string, props *ClusterRoleBindingProps) {
	plus34.NewClusterRoleBinding_Override(binding, scope, id, props)
}

func NewClusterRole_Override(role ClusterRole, scope constructs.Construct, id *string, props *ClusterRoleProps) {
	plus34.NewClusterRole_Override(role, scope, id, props)
}

func NewConfigMap(scope constructs.Construct, id *string, props *ConfigMapProps) ConfigMap {
	return plus34.NewConfigMap(scope, id, props)
}

func NewConfigMap_Override(c ConfigMap, scope constructs.Construct, id *string, props *ConfigMapProps) {
	plus34.NewConfigMap_Override(c, scope, id, props)
}

func NewContainer(props *ContainerProps) Container {
	return plus34.NewContainer(props)
}

func NewContainerSecurityContext(props *ContainerSecurityContextProps) ContainerSecurityContext {
	return plus34.NewContainerSecurityContext(props)
}

func NewContainerSecurityContext_Override(context ContainerSecurityContext, props *ContainerSecurityContextProps) {
	plus34.NewContainerSecurityContext_Override(context, props)
}

func NewContainer_Override(container Container, props *ContainerProps) {
	plus34.NewContainer_Override(container, props)
}

func NewCronJob(scope constructs.Construct, id *string, props *CronJobProps) CronJob {
	return plus34.NewCronJob(scope, id, props)
}

func NewCronJob_Override(job CronJob, scope constructs.Construct, id *string, props *CronJobProps) {
	plus34.NewCronJob_Override(job, scope, id, props)
}

func NewDaemonSet(scope constructs.Construct, id *string, props *DaemonSetProps) DaemonSet {
	return plus34.NewDaemonSet(scope, id, props)
}

func NewDaemonSet_Override(daemonSet DaemonSet, scope constructs.Construct, id *string, props *DaemonSetProps) {
	plus34.NewDaemonSet_Override(daemonSet, scope, id, props)
}

func NewDeployment(scope constructs.Construct, id *string, props *DeploymentProps) Deployment {
	return plus34.NewDeployment(scope, id, props)
}

func NewDeployment_Override(d Deployment, scope constructs.Construct, id *string, props *DeploymentProps) {
	plus34.NewDeployment_Override(d, scope, id, props)
}

func NewDockerConfigSecret(scope constructs.Construct, id *string, props *DockerConfigSecretProps) DockerConfigSecret {
	return plus34.NewDockerConfigSecret(scope, id, props)
}

func NewDockerConfigSecret_Override(secret DockerConfigSecret, scope constructs.Construct, id *string, props *DockerConfigSecretProps) {
	plus34.NewDockerConfigSecret_Override(secret, scope, id, props)
}

func NewEnv(sources *[]EnvFrom, variables *map[string]EnvValue) Env {
	return plus34.NewEnv(sources, variables)
}

func NewEnvFrom(configMap IConfigMap, prefix *string, secret ISecret) EnvFrom {
	return plus34.NewEnvFrom(configMap, prefix, secret)
}

func NewEnvFrom_Override(env EnvFrom, configMap IConfigMap, prefix *string, secret ISecret) {
	plus34.NewEnvFrom_Override(env, configMap, prefix, secret)
}

func NewEnv_Override(env Env, sources *[]EnvFrom, variables *map[string]EnvValue) {
	plus34.NewEnv_Override(env, sources, variables)
}

func NewGCEPersistentDiskPersistentVolume(scope constructs.Construct, id *string, props *GCEPersistentDiskPersistentVolumeProps) GCEPersistentDiskPersistentVolume {
	return plus34.NewGCEPersistentDiskPersistentVolume(scope, id, props)
}

func NewGCEPersistentDiskPersistentVolume_Override(volume GCEPersistentDiskPersistentVolume, scope constructs.Construct, id *string, props *GCEPersistentDiskPersistentVolumeProps) {
	plus34.NewGCEPersistentDiskPersistentVolume_Override(volume, scope, id, props)
}

func NewHorizontalPodAutoscaler(scope constructs.Construct, id *string, props *HorizontalPodAutoscalerProps) HorizontalPodAutoscaler {
	return plus34.NewHorizontalPodAutoscaler(scope, id, props)
}

func NewHorizontalPodAutoscaler_Override(autoscaler HorizontalPodAutoscaler, scope constructs.Construct, id *string, props *HorizontalPodAutoscalerProps) {
	plus34.NewHorizontalPodAutoscaler_Override(autoscaler, scope, id, props)
}

func NewIngress(scope constructs.Construct, id *string, props *IngressProps) Ingress {
	return plus34.NewIngress(scope, id, props)
}

func NewIngress_Override(ingress Ingress, scope constructs.Construct, id *string, props *IngressProps) {
	plus34.NewIngress_Override(ingress, scope, id, props)
}

func NewJob(scope constructs.Construct, id *string, props *JobProps) Job {
	return plus34.NewJob(scope, id, props)
}

func NewJob_Override(job Job, scope constructs.Construct, id *string, props *JobProps) {
	plus34.NewJob_Override(job, scope, id, props)
}

func NewLabeledNode(selector *[]NodeLabelQuery) LabeledNode {
	return plus34.NewLabeledNode(selector)
}

func NewLabeledNode_Override(node LabeledNode, selector *[]NodeLabelQuery) {
	plus34.NewLabeledNode_Override(node, selector)
}

func NewNamedNode(name *string) NamedNode {
	return plus34.NewNamedNode(name)
}

func NewNamedNode_Override(node NamedNode, name *string) {
	plus34.NewNamedNode_Override(node, name)
}

func NewNamespace(scope constructs.Construct, id *string, props *NamespaceProps) Namespace {
	return plus34.NewNamespace(scope, id, props)
}

func NewNamespace_Override(namespace Namespace, scope constructs.Construct, id *string, props *NamespaceProps) {
	plus34.NewNamespace_Override(namespace, scope, id, props)
}

func NewNamespaces(scope constructs.Construct, id *string, expressions *[]LabelExpression, names *[]*string, labels *map[string]*string) Namespaces {
	return plus34.NewNamespaces(scope, id, expressions, names, labels)
}

func NewNamespaces_Override(namespaces Namespaces, scope constructs.Construct, id *string, expressions *[]LabelExpression, names *[]*string, labels *map[string]*string) {
	plus34.NewNamespaces_Override(namespaces, scope, id, expressions, names, labels)
}

func NewNetworkPolicy(scope constructs.Construct, id *string, props *NetworkPolicyProps) NetworkPolicy {
	return plus34.NewNetworkPolicy(scope, id, props)
}

func NewNetworkPolicyPort(props *NetworkPolicyPortProps) NetworkPolicyPort {
	return plus34.NewNetworkPolicyPort(props)
}

func NewNetworkPolicyPort_Override(port NetworkPolicyPort, props *NetworkPolicyPortProps) {
	plus34.NewNetworkPolicyPort_Override(port, props)
}

func NewNetworkPolicy_Override(policy NetworkPolicy, scope constructs.Construct, id *string, props *NetworkPolicyProps) {
	plus34.NewNetworkPolicy_Override(policy, scope, id, props)
}

func NewNode() Node {
	return plus34.NewNode()
}

func NewNode_Override(arg0 Node) {
	plus34.NewNode_Override(arg0)
}

func NewPersistentVolume(scope constructs.Construct, id *string, props *PersistentVolumeProps) PersistentVolume {
	return plus34.NewPersistentVolume(scope, id, props)
}

func NewPersistentVolumeClaim(scope constructs.Construct, id *string, props *PersistentVolumeClaimProps) PersistentVolumeClaim {
	return plus34.NewPersistentVolumeClaim(scope, id, props)
}

func NewPersistentVolumeClaim_Override(claim PersistentVolumeClaim, scope constructs.Construct, id *string, props *PersistentVolumeClaimProps) {
	plus34.NewPersistentVolumeClaim_Override(claim, scope, id, props)
}

func NewPersistentVolume_Override(volume PersistentVolume, scope constructs.Construct, id *string, props *PersistentVolumeProps) {
	plus34.NewPersistentVolume_Override(volume, scope, id, props)
}

func NewPod(scope constructs.Construct, id *string, props *PodProps) Pod {
	return plus34.NewPod(scope, id, props)
}

func NewPodConnections(instance AbstractPod) PodConnections {
	return plus34.NewPodConnections(instance)
}

func NewPodConnections_Override(connections PodConnections, instance AbstractPod) {
	plus34.NewPodConnections_Override(connections, instance)
}

func NewPodDns(props *PodDnsProps) PodDns {
	return plus34.NewPodDns(props)
}

func NewPodDns_Override(dns PodDns, props *PodDnsProps) {
	plus34.NewPodDns_Override(dns, props)
}

func NewPodScheduling(instance AbstractPod) PodScheduling {
	return plus34.NewPodScheduling(instance)
}

func NewPodScheduling_Override(scheduling PodScheduling, instance AbstractPod) {
	plus34.NewPodScheduling_Override(scheduling, instance)
}

func NewPodSecurityContext(props *PodSecurityContextProps) PodSecurityContext {
	return plus34.NewPodSecurityContext(props)
}

func NewPodSecurityContext_Override(context PodSecurityContext, props *PodSecurityContextProps) {
	plus34.NewPodSecurityContext_Override(context, props)
}

func NewPod_Override(pod Pod, scope constructs.Construct, id *string, props *PodProps) {
	plus34.NewPod_Override(pod, scope, id, props)
}

func NewPods(scope constructs.Construct, id *string, expressions *[]LabelExpression, labels *map[string]*string, namespaces INamespaceSelector) Pods {
	return plus34.NewPods(scope, id, expressions, labels, namespaces)
}

func NewPods_Override(pods Pods, scope constructs.Construct, id *string, expressions *[]LabelExpression, labels *map[string]*string, namespaces INamespaceSelector) {
	plus34.NewPods_Override(pods, scope, id, expressions, labels, namespaces)
}

func NewResourcePermissions(instance Resource) ResourcePermissions {
	return plus34.NewResourcePermissions(instance)
}

func NewResourcePermissions_Override(permissions ResourcePermissions, instance Resource) {
	plus34.NewResourcePermissions_Override(permissions, instance)
}

func NewResource_Override(arg0 Resource, arg1 constructs.Construct, arg2 *string) {
	plus34.NewResource_Override(arg0, arg1, arg2)
}

func NewRole(scope constructs.Construct, id *string, props *RoleProps) Role {
	return plus34.NewRole(scope, id, props)
}

func NewRoleBinding(scope constructs.Construct, id *string, props *RoleBindingProps) RoleBinding {
	return plus34.NewRoleBinding(scope, id, props)
}

func NewRoleBinding_Override(binding RoleBinding, scope constructs.Construct, id *string, props *RoleBindingProps) {
	plus34.NewRoleBinding_Override(binding, scope, id, props)
}

func NewRole_Override(role Role, scope constructs.Construct, id *string, props *RoleProps) {
	plus34.NewRole_Override(role, scope, id, props)
}

func NewSecret(scope constructs.Construct, id *string, props *SecretProps) Secret {
	return plus34.NewSecret(scope, id, props)
}

func NewSecret_Override(secret Secret, scope constructs.Construct, id *string, props *SecretProps) {
	plus34.NewSecret_Override(secret, scope, id, props)
}

func NewService(scope constructs.Construct, id *string, props *ServiceProps) Service {
	return plus34.NewService(scope, id, props)
}

func NewServiceAccount(scope constructs.Construct, id *string, props *ServiceAccountProps) ServiceAccount {
	return plus34.NewServiceAccount(scope, id, props)
}

func NewServiceAccountTokenSecret(scope constructs.Construct, id *string, props *ServiceAccountTokenSecretProps) ServiceAccountTokenSecret {
	return plus34.NewServiceAccountTokenSecret(scope, id, props)
}

func NewServiceAccountTokenSecret_Override(secret ServiceAccountTokenSecret, scope constructs.Construct, id *string, props *ServiceAccountTokenSecretProps) {
	plus34.NewServiceAccountTokenSecret_Override(secret, scope, id, props)
}

func NewServiceAccount_Override(account ServiceAccount, scope constructs.Construct, id *string, props *ServiceAccountProps) {
	plus34.NewServiceAccount_Override(account, scope, id, props)
}

func NewService_Override(service Service, scope constructs.Construct, id *string, props *ServiceProps) {
	plus34.NewService_Override(service, scope, id, props)
}

func NewSshAuthSecret(scope constructs.Construct, id *string, props *SshAuthSecretProps) SshAuthSecret {
	return plus34.NewSshAuthSecret(scope, id, props)
}

func NewSshAuthSecret_Override(secret SshAuthSecret, scope constructs.Construct, id *string, props *SshAuthSecretProps) {
	plus34.NewSshAuthSecret_Override(secret, scope, id, props)
}

func NewStatefulSet(scope constructs.Construct, id *string, props *StatefulSetProps) StatefulSet {
	return plus34.NewStatefulSet(scope, id, props)
}

func NewStatefulSet_Override(s StatefulSet, scope constructs.Construct, id *string, props *StatefulSetProps) {
	plus34.NewStatefulSet_Override(s, scope, id, props)
}

func NewTaintedNode(selector *[]NodeTaintQuery) TaintedNode {
	return plus34.NewTaintedNode(selector)
}

func NewTaintedNode_Override(node TaintedNode, selector *[]NodeTaintQuery) {
	plus34.NewTaintedNode_Override(node, selector)
}

func NewTlsSecret(scope constructs.Construct, id *string, props *TlsSecretProps) TlsSecret {
	return plus34.NewTlsSecret(scope, id, props)
}

func NewTlsSecret_Override(secret TlsSecret, scope constructs.Construct, id *string, props *TlsSecretProps) {
	plus34.NewTlsSecret_Override(secret, scope, id, props)
}

func NewWorkloadScheduling(instance AbstractPod) WorkloadScheduling {
	return plus34.NewWorkloadScheduling(instance)
}

func NewWorkloadScheduling_Override(scheduling WorkloadScheduling, instance AbstractPod) {
	plus34.NewWorkloadScheduling_Override(scheduling, instance)
}

func NewWorkload_Override(arg0 Workload, arg1 constructs.Construct, arg2 *string, arg3 *WorkloadProps) {
	plus34.NewWorkload_Override(arg0, arg1, arg2, arg3)
}

func NodeLabelQuery_DoesNotExist(key *string) NodeLabelQuery {
	return plus34.NodeLabelQuery_DoesNotExist(key)
}

func NodeLabelQuery_Exists(key *string) NodeLabelQuery {
	return plus34.NodeLabelQuery_Exists(key)
}

func NodeLabelQuery_Gt(key *string, values *[]*string) NodeLabelQuery {
	return plus34.NodeLabelQuery_Gt(key, values)
}

func NodeLabelQuery_In(key *string, values *[]*string) NodeLabelQuery {
	return plus34.NodeLabelQuery_In(key, values)
}

func NodeLabelQuery_Is(key, value *string) NodeLabelQuery {
	return plus34.NodeLabelQuery_Is(key, value)
}

func NodeLabelQuery_Lt(key *string, values *[]*string) NodeLabelQuery {
	return plus34.NodeLabelQuery_Lt(key, values)
}

func NodeLabelQuery_NotIn(key *string, values *[]*string) NodeLabelQuery {
	return plus34.NodeLabelQuery_NotIn(key, values)
}

func NodeTaintQuery_Any() NodeTaintQuery {
	return plus34.NodeTaintQuery_Any()
}

func NodeTaintQuery_Exists(key *string, options *NodeTaintQueryOptions) NodeTaintQuery {
	return plus34.NodeTaintQuery_Exists(key, options)
}

func NodeTaintQuery_Is(key, value *string, options *NodeTaintQueryOptions) NodeTaintQuery {
	return plus34.NodeTaintQuery_Is(key, value, options)
}

func Node_Labeled(selectors ...NodeLabelQuery) LabeledNode {
	return plus34.Node_Labeled(selectors...)
}

func Node_Named(name *string) NamedNode {
	return plus34.Node_Named(name)
}

func Node_Tainted(selector ...NodeTaintQuery) TaintedNode {
	return plus34.Node_Tainted(selector...)
}

func NonApiResource_Of(url *string) NonApiResource {
	return plus34.NonApiResource_Of(url)
}

func PercentOrAbsolute_Absolute(value *float64) PercentOrAbsolute {
	return plus34.PercentOrAbsolute_Absolute(value)
}

func PercentOrAbsolute_Percent(value *float64) PercentOrAbsolute {
	return plus34.PercentOrAbsolute_Percent(value)
}

func PersistentVolumeClaim_FromClaimName(scope constructs.Construct, id, name *string) IPersistentVolumeClaim {
	return plus34.PersistentVolumeClaim_FromClaimName(scope, id, name)
}

func PersistentVolumeClaim_IsConstruct(x interface{}) *bool {
	return plus34.PersistentVolumeClaim_IsConstruct(x)
}

func PersistentVolume_FromPersistentVolumeName(scope constructs.Construct, id, name *string) IPersistentVolume {
	return plus34.PersistentVolume_FromPersistentVolumeName(scope, id, name)
}

func PersistentVolume_IsConstruct(x interface{}) *bool {
	return plus34.PersistentVolume_IsConstruct(x)
}

func Pod_ADDRESS_LABEL() *string {
	return plus34.Pod_ADDRESS_LABEL()
}

func Pod_IsConstruct(x interface{}) *bool {
	return plus34.Pod_IsConstruct(x)
}

func Pods_All(scope constructs.Construct, id *string, options *PodsAllOptions) Pods {
	return plus34.Pods_All(scope, id, options)
}

func Pods_IsConstruct(x interface{}) *bool {
	return plus34.Pods_IsConstruct(x)
}

func Pods_Select(scope constructs.Construct, id *string, options *PodsSelectOptions) Pods {
	return plus34.Pods_Select(scope, id, options)
}

func Probe_FromCommand(command *[]*string, options *CommandProbeOptions) Probe {
	return plus34.Probe_FromCommand(command, options)
}

func Probe_FromGrpc(options *GrpcProbeOptions) Probe {
	return plus34.Probe_FromGrpc(options)
}

func Probe_FromHttpGet(path *string, options *HttpGetProbeOptions) Probe {
	return plus34.Probe_FromHttpGet(path, options)
}

func Probe_FromTcpSocket(options *TcpSocketProbeOptions) Probe {
	return plus34.Probe_FromTcpSocket(options)
}

func Replicas_Absolute(value *float64) Replicas {
	return plus34.Replicas_Absolute(value)
}

func Replicas_Percent(value *float64) Replicas {
	return plus34.Replicas_Percent(value)
}

func Resource_IsConstruct(x interface{}) *bool {
	return plus34.Resource_IsConstruct(x)
}

func RoleBinding_IsConstruct(x interface{}) *bool {
	return plus34.RoleBinding_IsConstruct(x)
}

func Role_FromRoleName(scope constructs.Construct, id, name *string) IRole {
	return plus34.Role_FromRoleName(scope, id, name)
}

func Role_IsConstruct(x interface{}) *bool {
	return plus34.Role_IsConstruct(x)
}

func Secret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.Secret_FromSecretName(scope, id, name)
}

func Secret_IsConstruct(x interface{}) *bool {
	return plus34.Secret_IsConstruct(x)
}

func ServiceAccountTokenSecret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.ServiceAccountTokenSecret_FromSecretName(scope, id, name)
}

func ServiceAccountTokenSecret_IsConstruct(x interface{}) *bool {
	return plus34.ServiceAccountTokenSecret_IsConstruct(x)
}

func ServiceAccount_FromServiceAccountName(scope constructs.Construct, id, name *string, options *FromServiceAccountNameOptions) IServiceAccount {
	return plus34.ServiceAccount_FromServiceAccountName(scope, id, name, options)
}

func ServiceAccount_IsConstruct(x interface{}) *bool {
	return plus34.ServiceAccount_IsConstruct(x)
}

func Service_IsConstruct(x interface{}) *bool {
	return plus34.Service_IsConstruct(x)
}

func SshAuthSecret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.SshAuthSecret_FromSecretName(scope, id, name)
}

func SshAuthSecret_IsConstruct(x interface{}) *bool {
	return plus34.SshAuthSecret_IsConstruct(x)
}

func StatefulSetUpdateStrategy_OnDelete() StatefulSetUpdateStrategy {
	return plus34.StatefulSetUpdateStrategy_OnDelete()
}

func StatefulSetUpdateStrategy_RollingUpdate(options *StatefulSetUpdateStrategyRollingUpdateOptions) StatefulSetUpdateStrategy {
	return plus34.StatefulSetUpdateStrategy_RollingUpdate(options)
}

func StatefulSet_IsConstruct(x interface{}) *bool {
	return plus34.StatefulSet_IsConstruct(x)
}

func TlsSecret_FromSecretName(scope constructs.Construct, id, name *string) ISecret {
	return plus34.TlsSecret_FromSecretName(scope, id, name)
}

func TlsSecret_IsConstruct(x interface{}) *bool {
	return plus34.TlsSecret_IsConstruct(x)
}

func Topology_Custom(key *string) Topology {
	return plus34.Topology_Custom(key)
}

func Topology_HOSTNAME() Topology {
	return plus34.Topology_HOSTNAME()
}

func Topology_REGION() Topology {
	return plus34.Topology_REGION()
}

func Topology_ZONE() Topology {
	return plus34.Topology_ZONE()
}

func User_FromName(scope constructs.Construct, id, name *string) User {
	return plus34.User_FromName(scope, id, name)
}

func User_IsConstruct(x interface{}) *bool {
	return plus34.User_IsConstruct(x)
}

func Volume_FromAwsElasticBlockStore(scope constructs.Construct, id, volumeID *string, options *AwsElasticBlockStoreVolumeOptions) Volume {
	return plus34.Volume_FromAwsElasticBlockStore(scope, id, volumeID, options)
}

func Volume_FromAzureDisk(scope constructs.Construct, id, diskName, diskURI *string, options *AzureDiskVolumeOptions) Volume {
	return plus34.Volume_FromAzureDisk(scope, id, diskName, diskURI, options)
}

func Volume_FromConfigMap(scope constructs.Construct, id *string, configMap IConfigMap, options *ConfigMapVolumeOptions) Volume {
	return plus34.Volume_FromConfigMap(scope, id, configMap, options)
}

func Volume_FromCsi(scope constructs.Construct, id, driver *string, options *CsiVolumeOptions) Volume {
	return plus34.Volume_FromCsi(scope, id, driver, options)
}

func Volume_FromEmptyDir(scope constructs.Construct, id, name *string, options *EmptyDirVolumeOptions) Volume {
	return plus34.Volume_FromEmptyDir(scope, id, name, options)
}

func Volume_FromGcePersistentDisk(scope constructs.Construct, id, pdName *string, options *GCEPersistentDiskVolumeOptions) Volume {
	return plus34.Volume_FromGcePersistentDisk(scope, id, pdName, options)
}

func Volume_FromHostPath(scope constructs.Construct, id, name *string, options *HostPathVolumeOptions) Volume {
	return plus34.Volume_FromHostPath(scope, id, name, options)
}

func Volume_FromName(scope constructs.Construct, id, name *string) Volume {
	return plus34.Volume_FromName(scope, id, name)
}

func Volume_FromNfs(scope constructs.Construct, id, name *string, options *NfsVolumeOptions) Volume {
	return plus34.Volume_FromNfs(scope, id, name, options)
}

func Volume_FromPersistentVolumeClaim(scope constructs.Construct, id *string, claim IPersistentVolumeClaim, options *PersistentVolumeClaimVolumeOptions) Volume {
	return plus34.Volume_FromPersistentVolumeClaim(scope, id, claim, options)
}

func Volume_FromSecret(scope constructs.Construct, id *string, secret ISecret, options *SecretVolumeOptions) Volume {
	return plus34.Volume_FromSecret(scope, id, secret, options)
}

func Volume_IsConstruct(x interface{}) *bool {
	return plus34.Volume_IsConstruct(x)
}

func Workload_IsConstruct(x interface{}) *bool {
	return plus34.Workload_IsConstruct(x)
}
