package cdk8splus34

import (
	"fmt"
	"sort"

	"github.com/Chriscbr/purecdk8s/jsii"
)

// Network protocols.
type Protocol string

const (
	// TCP.
	Protocol_TCP Protocol = "TCP"
	// UDP.
	Protocol_UDP Protocol = "UDP"
	// SCTP.
	Protocol_SCTP Protocol = "SCTP"
)

type ImagePullPolicy string

const (
	// Every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image digest.
	//
	// If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet downloads (pulls) the image with the resolved digest, and uses that image to launch the container.
	//
	// Default is Always if ImagePullPolicy is omitted and either the image tag is :latest or the image tag is omitted.
	ImagePullPolicy_ALWAYS ImagePullPolicy = "ALWAYS"
	// The image is pulled only if it is not already present locally.
	//
	// Default is IfNotPresent if ImagePullPolicy is omitted and the image tag is present but not :latest.
	ImagePullPolicy_IF_NOT_PRESENT ImagePullPolicy = "IF_NOT_PRESENT"
	// The image is assumed to exist locally.
	//
	// No attempt is made to pull the image.
	ImagePullPolicy_NEVER ImagePullPolicy = "NEVER"
)

func imagePullPolicyManifestValue(value ImagePullPolicy) string {
	switch value {
	case ImagePullPolicy_ALWAYS:
		return "Always"
	case ImagePullPolicy_IF_NOT_PRESENT:
		return "IfNotPresent"
	case ImagePullPolicy_NEVER:
		return "Never"
	default:
		return string(value)
	}
}

// Represents a network port in a single container.
type ContainerPort struct {
	// Number of port to expose on the pod's IP address.
	//
	// This must be a valid port number, 0 < x < 65536.
	Number *float64 `field:"required" json:"number" yaml:"number"`
	// What host IP to bind the external port to. Default: - 127.0.0.1.
	HostIp *string `field:"optional" json:"hostIp" yaml:"hostIp"`
	// Number of port to expose on the host.
	//
	// If specified, this must be a valid port number, 0 < x < 65536. Most containers do not need this. Default: - auto generated by kubernetes and might change on restarts.
	HostPort *float64 `field:"optional" json:"hostPort" yaml:"hostPort"`
	// If specified, this must be an IANA_SVC_NAME and unique within the pod.
	//
	// Each named port in a pod must have a unique name. Name for the port that can be referred to by services. Default: - port is not named.
	Name *string `field:"optional" json:"name" yaml:"name"`
	// Protocol for port.
	//
	// Must be UDP, TCP, or SCTP. Defaults to "TCP". Default: Protocol.TCP
	Protocol Protocol `field:"optional" json:"protocol" yaml:"protocol"`
}

// Properties for creating a container.
type ContainerProps struct {
	// Docker image name.
	Image *string `field:"required" json:"image" yaml:"image"`
	// Name of the container specified as a DNS_LABEL.
	//
	// Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated. Default: 'main'.
	Name *string `field:"optional" json:"name" yaml:"name"`
	// Deprecated: - use `portNumber`.
	Port *float64 `field:"optional" json:"port" yaml:"port"`
	// Number of port to expose on the pod's IP address.
	//
	// This must be a valid port number, 0 < x < 65536.
	//
	// This is a convinience property if all you need a single TCP numbered port. In case more advanced configuartion is required, use the `ports` property.
	//
	// This port is added to the list of ports mentioned in the `ports` property. Default: - Only the ports mentiond in the `ports` property are exposed.
	PortNumber *float64 `field:"optional" json:"portNumber" yaml:"portNumber"`
	// List of ports to expose from this container. Default: - Only the port mentioned in the `portNumber` property is exposed.
	Ports *[]*ContainerPort `field:"optional" json:"ports" yaml:"ports"`
	// Entrypoint array.
	//
	// Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell Default: - The docker image's ENTRYPOINT.
	Command *[]*string `field:"optional" json:"command" yaml:"command"`
	// Arguments to the entrypoint. The docker image's CMD is used if `command` is not provided.
	//
	// Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not.
	//
	// Cannot be updated. See: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
	//
	// Default: [].
	Args *[]*string `field:"optional" json:"args" yaml:"args"`
	// Container's working directory.
	//
	// If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated. Default: - The container runtime's default.
	WorkingDir *string `field:"optional" json:"workingDir" yaml:"workingDir"`
	// Environment variables to set in the container. Default: - No environment variables.
	EnvVariables *map[string]EnvValue `field:"optional" json:"envVariables" yaml:"envVariables"`
	// List of sources to populate environment variables in the container.
	//
	// When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by the `envVariables` property with a duplicate key will take precedence. Default: - No sources.
	EnvFrom *[]EnvFrom `field:"optional" json:"envFrom" yaml:"envFrom"`
	// Image pull policy for this container. Default: ImagePullPolicy.ALWAYS
	ImagePullPolicy ImagePullPolicy `field:"optional" json:"imagePullPolicy" yaml:"imagePullPolicy"`
	// Periodic probe of container liveness.
	//
	// Container will be restarted if the probe fails. Default: - no liveness probe is defined.
	Liveness Probe `field:"optional" json:"liveness" yaml:"liveness"`
	// Determines when the container is ready to serve traffic. Default: - no readiness probe is defined.
	Readiness Probe `field:"optional" json:"readiness" yaml:"readiness"`
	// StartupProbe indicates that the Pod has successfully initialized.
	//
	// If specified, no other probes are executed until this completes successfully. Default: - If a port is provided, then knocks on that port to determine when the container is ready for readiness and liveness probe checks. Otherwise, no startup probe is defined.
	Startup Probe `field:"optional" json:"startup" yaml:"startup"`
	// Describes actions that the management system should take in response to container lifecycle events.
	Lifecycle *ContainerLifecycle `field:"optional" json:"lifecycle" yaml:"lifecycle"`
	// Compute resources (CPU and memory requests and limits) required by the container. See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	//
	// Default: cpu:
	//
	//	  request: 1000 millis
	//	  limit: 1500 millis
	//	memory:
	//	  request: 512 mebibytes
	//
	// limit: 2048 mebibytes.
	Resources *ContainerResources `field:"optional" json:"resources" yaml:"resources"`
	// Kubelet will start init containers with restartPolicy=Always in the order with other init containers, but instead of waiting for its completion, it will wait for the container startup completion Currently, only accepted value is Always. See: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
	//
	// Default: - no restart policy is defined and the pod restart policy is applied.
	RestartPolicy ContainerRestartPolicy `field:"optional" json:"restartPolicy" yaml:"restartPolicy"`
	// SecurityContext defines the security options the container should be run with.
	//
	// If set, the fields override equivalent fields of the pod's security context. See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
	//
	// Default: ensureNonRoot: true
	//
	//	privileged: false
	//	readOnlyRootFilesystem: true
	//	allowPrivilegeEscalation: false
	//	user: 25000
	//
	// group: 26000.
	SecurityContext *ContainerSecurityContextProps `field:"optional" json:"securityContext" yaml:"securityContext"`
	// Pod volumes to mount into the container's filesystem.
	//
	// Cannot be updated.
	VolumeMounts *[]*VolumeMount `field:"optional" json:"volumeMounts" yaml:"volumeMounts"`
}

// Optional properties of a container.
type ContainerOpts struct {
	// Name of the container specified as a DNS_LABEL.
	//
	// Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated. Default: 'main'.
	Name *string
	// Deprecated: - use `portNumber`.
	Port *float64
	// Number of port to expose on the pod's IP address.
	//
	// This must be a valid port number, 0 < x < 65536.
	//
	// This is a convinience property if all you need a single TCP numbered port. In case more advanced configuartion is required, use the `ports` property.
	//
	// This port is added to the list of ports mentioned in the `ports` property. Default: - Only the ports mentiond in the `ports` property are exposed.
	PortNumber *float64
	// List of ports to expose from this container. Default: - Only the port mentioned in the `portNumber` property is exposed.
	Ports *[]*ContainerPort
	// Entrypoint array.
	//
	// Not executed within a shell. The docker image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell Default: - The docker image's ENTRYPOINT.
	Command *[]*string
	// Arguments to the entrypoint. The docker image's CMD is used if `command` is not provided.
	//
	// Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not.
	//
	// Cannot be updated. See: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
	//
	// Default: [].
	Args *[]*string
	// Container's working directory.
	//
	// If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated. Default: - The container runtime's default.
	WorkingDir *string
	// Environment variables to set in the container. Default: - No environment variables.
	EnvVariables *map[string]EnvValue
	// List of sources to populate environment variables in the container.
	//
	// When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by the `envVariables` property with a duplicate key will take precedence. Default: - No sources.
	EnvFrom *[]EnvFrom
	// Image pull policy for this container. Default: ImagePullPolicy.ALWAYS
	ImagePullPolicy ImagePullPolicy
	// Periodic probe of container liveness.
	//
	// Container will be restarted if the probe fails. Default: - no liveness probe is defined.
	Liveness Probe
	// Determines when the container is ready to serve traffic. Default: - no readiness probe is defined.
	Readiness Probe
	// StartupProbe indicates that the Pod has successfully initialized.
	//
	// If specified, no other probes are executed until this completes successfully. Default: - If a port is provided, then knocks on that port to determine when the container is ready for readiness and liveness probe checks. Otherwise, no startup probe is defined.
	Startup Probe
	// Describes actions that the management system should take in response to container lifecycle events.
	Lifecycle *ContainerLifecycle
	// Compute resources (CPU and memory requests and limits) required by the container. See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	//
	// Default: cpu:
	//
	//	  request: 1000 millis
	//	  limit: 1500 millis
	//	memory:
	//	  request: 512 mebibytes
	//
	// limit: 2048 mebibytes.
	Resources *ContainerResources
	// Kubelet will start init containers with restartPolicy=Always in the order with other init containers, but instead of waiting for its completion, it will wait for the container startup completion Currently, only accepted value is Always. See: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
	//
	// Default: - no restart policy is defined and the pod restart policy is applied.
	RestartPolicy ContainerRestartPolicy
	// SecurityContext defines the security options the container should be run with.
	//
	// If set, the fields override equivalent fields of the pod's security context. See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
	//
	// Default: ensureNonRoot: true
	//
	//	privileged: false
	//	readOnlyRootFilesystem: true
	//	allowPrivilegeEscalation: false
	//	user: 25000
	//
	// group: 26000.
	SecurityContext *ContainerSecurityContextProps
	// Pod volumes to mount into the container's filesystem.
	//
	// Cannot be updated.
	VolumeMounts *[]*VolumeMount
}

// A single application container that you want to run within a pod.
type Container interface {
	// Arguments to the entrypoint.
	//
	// Returns: a copy of the arguments array, cannot be modified.
	Args() *[]*string
	// Entrypoint array (the command to execute when the container starts).
	//
	// Returns: a copy of the entrypoint array, cannot be modified.
	Command() *[]*string
	// The container image.
	Image() *string
	// Image pull policy for this container.
	ImagePullPolicy() ImagePullPolicy
	// Volume mounts configured for this container.
	Mounts() *[]*VolumeMount
	// The name of the container.
	Name() *string
	// Deprecated: - use `portNumber`.
	Port() *float64
	// The port number that was configured for this container.
	//
	// If undefined, either the container doesn't expose a port, or its port configuration is stored in the `ports` field.
	PortNumber() *float64
	// Ports exposed by this containers.
	//
	// Returns a copy, use `addPort` to modify.
	Ports() *[]*ContainerPort
	// The working directory inside the container.
	WorkingDir() *string
	// The environment of the container.
	Env() Env
	// Compute resources (CPU and memory requests and limits) required by the container. See: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Resources() *ContainerResources
	// The restart policy of the container.
	RestartPolicy() ContainerRestartPolicy
	// The security context of the container.
	SecurityContext() ContainerSecurityContext
	// Add a port to expose from this container.
	AddPort(port *ContainerPort)
	// Mount a volume to a specific path so that it is accessible by the container.
	//
	// Every pod that is configured to use this container will autmoatically have access to the volume.
	Mount(path *string, storage IStorage, options *MountOptions)
}

type containerImpl struct {
	image           *string
	name            *string
	portNumber      *float64
	ports           []*ContainerPort
	command         *[]*string
	args            *[]*string
	workingDir      *string
	env             *envImpl
	mounts          []*VolumeMount
	pullPolicy      ImagePullPolicy
	liveness        Probe
	readiness       Probe
	startup         Probe
	lifecycle       *ContainerLifecycle
	resources       *ContainerResources
	restartPolicy   ContainerRestartPolicy
	securityContext ContainerSecurityContext
}

func NewContainer(props *ContainerProps) Container {
	if props == nil || props.Image == nil {
		panic("props.image is required")
	}
	return newContainer(props)
}

func NewContainer_Override(container Container, props *ContainerProps) {
	applyOverride(container, NewContainer(props), "Container")
}

func newContainer(props *ContainerProps) *containerImpl {
	if props.Port != nil && props.PortNumber != nil {
		panic("Either 'port' or 'portNumber' is allowed. Use 'portNumber' since 'port' is deprecated")
	}
	name := props.Name
	if name == nil {
		name = jsii.String("main")
	}
	result := &containerImpl{
		image:           props.Image,
		name:            name,
		command:         props.Command,
		args:            props.Args,
		workingDir:      props.WorkingDir,
		pullPolicy:      props.ImagePullPolicy,
		liveness:        props.Liveness,
		readiness:       props.Readiness,
		startup:         props.Startup,
		lifecycle:       props.Lifecycle,
		resources:       normalizedContainerResources(props.Resources),
		restartPolicy:   props.RestartPolicy,
		securityContext: NewContainerSecurityContext(props.SecurityContext),
		env:             newEnv(props.EnvFrom, props.EnvVariables),
	}
	if result.pullPolicy == "" {
		result.pullPolicy = ImagePullPolicy_ALWAYS
	}
	if props.PortNumber != nil {
		result.portNumber = props.PortNumber
	} else {
		result.portNumber = props.Port
	}
	if result.portNumber != nil {
		result.ports = append(result.ports, &ContainerPort{Number: result.portNumber})
	}
	if props.Ports != nil {
		for _, port := range *props.Ports {
			if port != nil {
				result.AddPort(port)
			}
		}
	}
	if props.VolumeMounts != nil {
		for _, mount := range *props.VolumeMounts {
			if mount == nil || mount.Path == nil || mount.Volume == nil {
				panic("volume mount path and volume are required")
			}
			result.mounts = append(result.mounts, mount)
		}
	}
	return result
}

func (c *containerImpl) Args() *[]*string {
	return c.args
}

func (c *containerImpl) Command() *[]*string {
	return c.command
}

func (c *containerImpl) Image() *string {
	return c.image
}

func (c *containerImpl) ImagePullPolicy() ImagePullPolicy {
	return c.pullPolicy
}

func (c *containerImpl) Name() *string {
	return c.name
}

func (c *containerImpl) Port() *float64 {
	return c.portNumber
}

func (c *containerImpl) PortNumber() *float64 {
	return c.portNumber
}

func (c *containerImpl) WorkingDir() *string {
	return c.workingDir
}

func (c *containerImpl) Env() Env {
	return c.env
}

func (c *containerImpl) Resources() *ContainerResources {
	return c.resources
}

func (c *containerImpl) RestartPolicy() ContainerRestartPolicy {
	return c.restartPolicy
}

func (c *containerImpl) SecurityContext() ContainerSecurityContext {
	return c.securityContext
}

func (c *containerImpl) Ports() *[]*ContainerPort {
	values := append([]*ContainerPort(nil), c.ports...)
	return &values
}

func (c *containerImpl) Mounts() *[]*VolumeMount {
	values := append([]*VolumeMount(nil), c.mounts...)
	return &values
}

func (c *containerImpl) AddPort(port *ContainerPort) {
	if port == nil || port.Number == nil {
		panic("container port number is required")
	}
	protocol := port.Protocol
	if protocol == "" {
		protocol = Protocol_TCP
	}
	for _, existing := range c.ports {
		if port.Name != nil && *port.Name != "" && existing.Name != nil && *existing.Name == *port.Name {
			panic("Port with name " + *port.Name + " already exists")
		}
		existingProtocol := existing.Protocol
		if existingProtocol == "" {
			existingProtocol = Protocol_TCP
		}
		if *existing.Number == *port.Number && existingProtocol == protocol {
			panic(fmt.Sprintf("Port with number %s and protocol %s already exists", formatNumber(*port.Number), protocol))
		}
	}
	c.ports = append(c.ports, port)
}

func (c *containerImpl) Mount(path *string, storage IStorage, options *MountOptions) {
	if path == nil || storage == nil {
		panic("path and storage are required")
	}
	volume := storage.AsVolume()
	c.mounts = append(c.mounts, &VolumeMount{Path: path, Volume: volume, ReadOnly: optionsReadOnly(options), Propagation: optionsPropagation(options), SubPath: optionsSubPath(options), SubPathExpr: optionsSubPathExpr(options)})
}

func optionsReadOnly(options *MountOptions) *bool {
	if options == nil {
		return nil
	}
	return options.ReadOnly
}

func optionsPropagation(options *MountOptions) MountPropagation {
	if options == nil {
		return ""
	}
	return options.Propagation
}

func optionsSubPath(options *MountOptions) *string {
	if options == nil {
		return nil
	}
	return options.SubPath
}

func optionsSubPathExpr(options *MountOptions) *string {
	if options == nil {
		return nil
	}
	return options.SubPathExpr
}

func (c *containerImpl) toManifest() map[string]interface{} {
	ports := make([]interface{}, 0, len(c.ports))
	for _, port := range c.ports {
		entry := map[string]interface{}{"containerPort": port.Number}
		if port.Name != nil {
			entry["name"] = port.Name
		}
		if port.HostIp != nil {
			entry["hostIP"] = port.HostIp
		}
		if port.HostPort != nil {
			entry["hostPort"] = port.HostPort
		}
		if port.Protocol != "" {
			entry["protocol"] = string(port.Protocol)
		}
		ports = append(ports, entry)
	}
	mounts := make([]interface{}, 0, len(c.mounts))
	for _, mount := range c.mounts {
		entry := map[string]interface{}{"name": mount.Volume.Name(), "mountPath": mount.Path}
		if mount.ReadOnly != nil {
			entry["readOnly"] = mount.ReadOnly
		}
		if mount.Propagation != "" {
			entry["mountPropagation"] = mountPropagationManifest(mount.Propagation)
		}
		if mount.SubPath != nil {
			entry["subPath"] = mount.SubPath
		}
		if mount.SubPathExpr != nil {
			entry["subPathExpr"] = mount.SubPathExpr
		}
		mounts = append(mounts, entry)
	}
	env := make([]interface{}, 0, len(c.env.variables))
	keys := make([]string, 0, len(c.env.variables))
	for key := range c.env.variables {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := c.env.variables[key]
		entry := map[string]interface{}{"name": key}
		if value.Value() != nil {
			entry["value"] = value.Value()
		}
		if value.ValueFrom() != nil {
			entry["valueFrom"] = value.ValueFrom()
		}
		env = append(env, entry)
	}
	result := map[string]interface{}{
		"image":           c.image,
		"name":            c.name,
		"imagePullPolicy": imagePullPolicyManifestValue(c.pullPolicy),
		"securityContext": c.securityContext.toManifest(),
	}
	if resources := containerResourcesManifest(c.resources); len(resources) > 0 {
		result["resources"] = resources
	}
	if c.command != nil {
		result["command"] = c.command
	}
	if c.args != nil {
		result["args"] = c.args
	}
	if c.workingDir != nil {
		result["workingDir"] = c.workingDir
	}
	if len(ports) > 0 {
		result["ports"] = ports
	}
	if len(mounts) > 0 {
		result["volumeMounts"] = mounts
	}
	if len(env) > 0 {
		result["env"] = env
	}
	if len(c.env.sources) > 0 {
		sources := make([]interface{}, 0, len(c.env.sources))
		for _, source := range c.env.sources {
			if source == nil {
				panic("environment source is required")
			}
			sources = append(sources, source.toManifest())
		}
		result["envFrom"] = sources
	}
	if c.lifecycle != nil {
		lifecycle := map[string]interface{}{}
		if c.lifecycle.PostStart != nil {
			lifecycle["postStart"] = c.lifecycle.PostStart.toManifest(c)
		}
		if c.lifecycle.PreStop != nil {
			lifecycle["preStop"] = c.lifecycle.PreStop.toManifest(c)
		}
		if len(lifecycle) > 0 {
			result["lifecycle"] = lifecycle
		}
	}
	if c.portNumber != nil {
		result["startupProbe"] = map[string]interface{}{
			"failureThreshold": 3,
			"tcpSocket":        map[string]interface{}{"port": c.portNumber},
		}
	}
	if c.liveness != nil {
		result["livenessProbe"] = c.liveness.toManifest(c)
	}
	if c.readiness != nil {
		result["readinessProbe"] = c.readiness.toManifest(c)
	}
	if c.startup != nil {
		result["startupProbe"] = c.startup.toManifest(c)
	}
	if c.restartPolicy != "" {
		result["restartPolicy"] = containerRestartPolicyManifest(c.restartPolicy)
	}
	return result
}

// Utility class for creating reading env values from various sources.
type EnvValue interface {
	Value() interface{}
	ValueFrom() interface{}
}

type envValue struct{ value, valueFrom interface{} }

func (v *envValue) Value() interface{} {
	return v.value
}

func (v *envValue) ValueFrom() interface{} {
	return v.valueFrom
}

// Create a value from the given argument.
func EnvValue_FromValue(value *string) EnvValue {
	if value == nil {
		panic("value is required")
	}
	return &envValue{value: value}
}

// Container environment variables.
type Env interface {
	// The list of sources used to populate the container environment, in addition to the `variables`.
	//
	// Returns a copy. To add a source use `container.env.copyFrom()`.
	Sources() *[]EnvFrom
	// The environment variables for this container.
	//
	// Returns a copy. To add environment variables use `container.env.addVariable()`.
	Variables() *map[string]EnvValue
	// Add a single variable by name and value.
	//
	// The variable value can come from various dynamic sources such a secrets of config maps. Use `EnvValue.fromXXX` to select sources.
	AddVariable(name *string, value EnvValue)
	// Add a collection of variables by copying from another source.
	//
	// Use `Env.fromXXX` functions to select sources.
	CopyFrom(from EnvFrom)
}

type envImpl struct {
	sources   []EnvFrom
	variables map[string]EnvValue
}

func NewEnv(sources *[]EnvFrom, variables *map[string]EnvValue) Env {
	return newEnv(sources, variables)
}

func NewEnv_Override(env Env, sources *[]EnvFrom, variables *map[string]EnvValue) {
	applyOverride(env, NewEnv(sources, variables), "Env")
}

func newEnv(sources *[]EnvFrom, variables *map[string]EnvValue) *envImpl {
	values := make(map[string]EnvValue)
	if variables != nil {
		for name, value := range *variables {
			if value == nil {
				panic("environment variable value is required")
			}
			values[name] = value
		}
	}
	result := &envImpl{variables: values}
	if sources != nil {
		for _, source := range *sources {
			if source == nil {
				panic("environment source is required")
			}
			result.sources = append(result.sources, source)
		}
	}
	return result
}

func (e *envImpl) Sources() *[]EnvFrom {
	values := append([]EnvFrom(nil), e.sources...)
	return &values
}

func (e *envImpl) Variables() *map[string]EnvValue {
	values := make(map[string]EnvValue, len(e.variables))
	for name, value := range e.variables {
		values[name] = value
	}
	return &values
}

func (e *envImpl) AddVariable(name *string, value EnvValue) {
	if name == nil || *name == "" || value == nil {
		panic("environment variable name and value are required")
	}
	e.variables[*name] = value
}

func (e *envImpl) CopyFrom(from EnvFrom) {
	if from == nil {
		panic("environment source is required")
	}
	e.sources = append(e.sources, from)
}

// Options to specify an envionment variable value from a ConfigMap key.
type EnvValueFromConfigMapOptions struct {
	// Specify whether the ConfigMap or its key must be defined. Default: false.
	Optional *bool `field:"optional" json:"optional" yaml:"optional"`
}

// Create a value by reading a specific key inside a config map.
func EnvValue_FromConfigMap(configMap IConfigMap, key *string, options *EnvValueFromConfigMapOptions) EnvValue {
	if configMap == nil || key == nil {
		panic("configMap and key are required")
	}
	ref := map[string]interface{}{"name": configMap.Name(), "key": key}
	if options != nil && options.Optional != nil {
		ref["optional"] = options.Optional
	}
	return &envValue{valueFrom: map[string]interface{}{"configMapKeyRef": ref}}
}
