//go:build ignore

// forward-cdk8splus regenerates the high-level cdk8s+ forwarding packages
// from the implemented 1.34 API. Kubernetes 1.35 and 1.36 keep that API,
// while exposing their own generated k8s packages.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const sourcePackage = "cdk8splus34/v2"

type function struct {
	name  string
	type_ *ast.FuncType
}

type importPath struct {
	alias string
	path  string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: go run scripts/forward-cdk8splus.go <kubernetes-minor-version> [...]")
		os.Exit(2)
	}
	types, constants, functions, imports, err := collect(sourcePackage)
	if err != nil {
		fail(err)
	}
	for _, minor := range os.Args[1:] {
		if !numeric(minor) {
			fail(fmt.Errorf("kubernetes-minor-version must be numeric: %q", minor))
		}
		content, err := render(minor, types, constants, functions, imports)
		if err != nil {
			fail(err)
		}
		filename := filepath.Join("cdk8splus"+minor, "v2", "forward.go")
		if err := os.WriteFile(filename, content, 0o644); err != nil {
			fail(err)
		}
		fmt.Println("generated " + filename)
	}
}

func collect(directory string) ([]string, []string, []function, map[string]importPath, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	var filenames []string
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filenames = append(filenames, filepath.Join(directory, entry.Name()))
	}
	sort.Strings(filenames)

	types := map[string]bool{}
	constants := map[string]bool{}
	functions := map[string]*ast.FuncType{}
	availableImports := map[string]importPath{}
	neededImports := map[string]bool{}
	fset := token.NewFileSet()
	for _, filename := range filenames {
		file, err := parser.ParseFile(fset, filename, nil, 0)
		if err != nil {
			return nil, nil, nil, nil, err
		}
		fileImports := map[string]importPath{}
		for _, specification := range file.Imports {
			path, err := strconv.Unquote(specification.Path.Value)
			if err != nil {
				return nil, nil, nil, nil, err
			}
			alias := packageAlias(path)
			if specification.Name != nil {
				alias = specification.Name.Name
			}
			if alias != "." && alias != "_" {
				fileImports[alias] = importPath{alias: alias, path: path}
			}
		}
		for _, declaration := range file.Decls {
			switch declaration := declaration.(type) {
			case *ast.FuncDecl:
				if declaration.Recv == nil && ast.IsExported(declaration.Name.Name) {
					functions[declaration.Name.Name] = declaration.Type
					ast.Inspect(declaration.Type, func(node ast.Node) bool {
						selector, ok := node.(*ast.SelectorExpr)
						if !ok {
							return true
						}
						identifier, ok := selector.X.(*ast.Ident)
						if !ok {
							return true
						}
						if imported, exists := fileImports[identifier.Name]; exists {
							availableImports[identifier.Name] = imported
							neededImports[identifier.Name] = true
						}
						return true
					})
				}
			case *ast.GenDecl:
				for _, specification := range declaration.Specs {
					switch specification := specification.(type) {
					case *ast.TypeSpec:
						if ast.IsExported(specification.Name.Name) {
							types[specification.Name.Name] = true
						}
					case *ast.ValueSpec:
						if declaration.Tok != token.CONST {
							continue
						}
						for _, name := range specification.Names {
							if ast.IsExported(name.Name) {
								constants[name.Name] = true
							}
						}
					}
				}
			}
		}
	}
	return sortedKeys(types), sortedKeys(constants), sortedFunctions(functions), selectImports(availableImports, neededImports), nil
}

func render(minor string, types, constants []string, functions []function, imports map[string]importPath) ([]byte, error) {
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by scripts/forward-cdk8splus.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "// Package cdk8splus%s forward-ports the native cdk8s+ high-level API to the\n", minor)
	fmt.Fprintf(&output, "// Kubernetes 1.%s schema. The high-level API is implemented by cdk8splus34;\n", minor)
	fmt.Fprintln(&output, "// users can use this package together with its version-specific k8s subpackage.")
	fmt.Fprintf(&output, "package cdk8splus%s\n\n", minor)
	fmt.Fprintln(&output, "import (")
	fmt.Fprintln(&output, "\tplus34 \"github.com/purecdk8s/purecdk8s/cdk8splus34/v2\"")
	var aliases []string
	for alias := range imports {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		imported := imports[alias]
		if filepath.Base(imported.path) == imported.alias {
			fmt.Fprintf(&output, "\t%q\n", imported.path)
		} else {
			fmt.Fprintf(&output, "\t%s %q\n", imported.alias, imported.path)
		}
	}
	fmt.Fprintln(&output, ")\n")

	for _, name := range types {
		fmt.Fprintf(&output, "type %s = plus34.%s\n", name, name)
	}
	if len(constants) > 0 {
		fmt.Fprintln(&output, "\nconst (")
		for _, name := range constants {
			fmt.Fprintf(&output, "\t%s = plus34.%s\n", name, name)
		}
		fmt.Fprintln(&output, ")")
	}
	for _, function := range functions {
		fmt.Fprintln(&output)
		fmt.Fprintf(&output, "func %s(%s)%s {\n", function.name, renderParameters(function.type_.Params), renderResults(function.type_.Results))
		call := "plus34." + function.name + "(" + renderArguments(function.type_.Params) + ")"
		if function.type_.Results == nil || len(function.type_.Results.List) == 0 {
			fmt.Fprintf(&output, "\t%s\n", call)
		} else {
			fmt.Fprintf(&output, "\treturn %s\n", call)
		}
		fmt.Fprintln(&output, "}")
	}
	return format.Source(output.Bytes())
}

func renderParameters(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}
	var parameters []string
	index := 0
	for _, field := range fields.List {
		var names []string
		for _, name := range field.Names {
			if name.Name == "_" {
				names = append(names, fmt.Sprintf("arg%d", index))
			} else {
				names = append(names, name.Name)
			}
			index++
		}
		if len(names) == 0 {
			names = append(names, fmt.Sprintf("arg%d", index))
			index++
		}
		parameters = append(parameters, strings.Join(names, ", ")+" "+expressionString(field.Type))
	}
	return strings.Join(parameters, ", ")
}

func renderArguments(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}
	var arguments []string
	index := 0
	for _, field := range fields.List {
		count := len(field.Names)
		if count == 0 {
			count = 1
		}
		variadic := false
		if _, ok := field.Type.(*ast.Ellipsis); ok {
			variadic = true
		}
		for position := 0; position < count; position++ {
			name := fmt.Sprintf("arg%d", index)
			if len(field.Names) > 0 && field.Names[position].Name != "_" {
				name = field.Names[position].Name
			}
			index++
			if variadic && position == count-1 {
				name += "..."
			}
			arguments = append(arguments, name)
		}
	}
	return strings.Join(arguments, ", ")
}

func renderResults(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	var results []string
	for _, field := range fields.List {
		prefix := ""
		if len(field.Names) > 0 {
			var names []string
			for _, name := range field.Names {
				names = append(names, name.Name)
			}
			prefix = strings.Join(names, ", ") + " "
		}
		results = append(results, prefix+expressionString(field.Type))
	}
	if len(results) == 1 {
		return " " + results[0]
	}
	return " (" + strings.Join(results, ", ") + ")"
}

func expressionString(expression ast.Expr) string {
	var output bytes.Buffer
	if err := printer.Fprint(&output, token.NewFileSet(), expression); err != nil {
		panic(err)
	}
	return output.String()
}

func sortedKeys(values map[string]bool) []string {
	result := make([]string, 0, len(values))
	for value := range values {
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}

func sortedFunctions(values map[string]*ast.FuncType) []function {
	var names []string
	for name := range values {
		names = append(names, name)
	}
	sort.Strings(names)
	result := make([]function, 0, len(names))
	for _, name := range names {
		result = append(result, function{name: name, type_: values[name]})
	}
	return result
}

func selectImports(available map[string]importPath, needed map[string]bool) map[string]importPath {
	result := map[string]importPath{}
	for name := range needed {
		result[name] = available[name]
	}
	return result
}

func numeric(value string) bool {
	return value != "" && strings.Trim(value, "0123456789") == ""
}

func packageAlias(path string) string {
	base := filepath.Base(path)
	if len(base) > 1 && base[0] == 'v' && numeric(base[1:]) {
		return filepath.Base(filepath.Dir(path))
	}
	return base
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
